### ISSUE TITLE
Make full SOLID-OIDC-compliance optional

### ISSUE THREAD

**Issue by woutermont** [inrupt/solid-client-authn-js#1121]
I'm not sure if this is something we want in a solid library, but is there any option or intention to make SOLID-OIDC-specific requirements (e.g. PKCE, and especially DPOP) optional? Since current OIDC providers are often easy to set up with WebID's, but harder to support those additional (security) measures without using an extra proxy/broker, we might provide compatibility with them and leave the secure choice up to the client developper (with sane default, of course).

### Expected functionality/enhancement
Add flags to enable/disable SOLID-OIDC-specific functionality like PKCE and DPOP.

### Actual functionality/enhancement
Public functions always automatically add SOLID-OIDC-specific headers and fields (unless I'm overseeing something, in which case please correct me).

### Use Cases
Support authentication via not-(yet)-SOLID-OIDC-compliant identity providers, leaving full security and compliance up to client developpers.

### Search terms you've used
`dpop`, `optional`

### Impacted environment
- [x] The browser
- [x] Node.js
- [x] Probably underlying in `oidc-client-ext`

**Comment by acoburn** [comment]
DPoP is already opt-in from the Solid-OIDC perspective. If a client sends a DPoP header to an authorization server's token endpoint, and that server doesn't understand that header, the response will include a `token_type` value of "Bearer" and no cnf claim will be present.

Realise, however, that _not_ using DPoP in Solid risks exposing a user's data to malicious actors, and making it easy to turn this feature off would not be best practice. An analogy would be the way browsers make it difficult for users to view HTTPS web pages with invalid or expired certificates

**Comment by woutermont** [comment]
@acoburn, you're entirely correct in pointing out the danger of providing such choices. On the other hand, I added 'with sane defaults' in the conviction that people specifically turning such defaults off would only do so in full awareness of their choice.

For the concrete case of DPoP: does the current authentication library implement this opt-in aspect? Currently, when I try to use the library with an IDP without DPoP support, two things seem to go wrong:

- The IDP does not add `dpop` to the allowed headers during CORS preflight of the token request, and so the browser blocks it.
- With the correct CORS headers mocked, the client is allowed to send the `dpop` header and indeed gets back a token with `token_type: Bearer`, but still sends that token as `Authorization: DPoP ...` to the resource server.

**Comment by nicolasmondada** [comment]
You can set the [tokenType](https://docs.inrupt.com/developer-tools/api/javascript/solid-client-authn-browser/interfaces/ILoginInputOptions.html#tokentype) to 'Bearer' if your IdP does not support DPoP. We haven't heard from customers asking to disable PKCE so far but we will keep this channel open for feedback.
