### ISSUE TITLE
Does not bundle well with Webpack

### ISSUE THREAD

**Issue by NSeydoux** [inrupt/solid-client-authn-js#122]
**Describe the bug**
If bundled with Webpack, throws an exception when any function is called. 

**To Reproduce**
1. Create a simple React app with `create-react-app`
2. `npm install @inrupt/solid-auth-fetcher`
3. Add `{fetch("http://www.perdu.com/").then(response => response.text).then(data => console.log(data))}` to the newly created app
4. `npm run start`
5. the browser should display the error `TypeError: Object(...) is not a function`.

**Expected behavior**
The functions should be available after bundling.

**Comment by jaxoncreed** [comment]
Wow it takes a super long time to start up the create-react-app project :( https://github.com/facebook/create-react-app/issues/2536

This issue is a bit strange. Working on it.

**Comment by jaxoncreed** [comment]
It seems as if the compiled index.js file does not list "module" at all.

**Comment by Vinnl** [comment]
This might be why both @ajacksified and I didn't manage to get it to work with lit-solid too.
