### ISSUE TITLE
Field [sessionId] for user [...] is not stored

### ISSUE THREAD

**Issue by NSeydoux** [inrupt/solid-client-authn-js#1242]
This issue comes from discussion in https://github.com/inrupt/solid-client-authn-js/issues/423, where a bug unrelated to the initial issue has been discovered by @matthieu-fesselier.

See https://github.com/inrupt/solid-client-authn-js/issues/423#issuecomment-810895015 and the subsequent conversation for more details.

### Search terms you've used

- sessionId
- not stored
  
### Impacted package

Which packages do you think might be impacted by the bug ?

- [X] solid-client-authn-browser
- [ ] solid-client-authn-node
- [ ] solid-client-authn-core
- [ ] oidc-client-ext
- [ ] Other (please specify): ...

### Bug description

The login process does not complete. The user is redirected fine to the identity provider, but when redirected back to the client app, instead of being logged in, the user is still logged out, and a message "Field [sessionId] for user [<some guid>] is not stored" is displayed.  

### To Reproduce

See linked issue

**Comment by Vinnl** [comment]
Also reported here: https://forum.solidproject.org/t/issues-with-logging-in-when-using-inrupt/4183

**Comment by NSeydoux** [comment]
Due to the nature of the bug, it's hard to reproduce it consistently. @matthieu-fesselier, could you try to see if `npm install @inrupt/solid-client-authn-browser@fixstore-race-condition` resolves your issue ? I can't reproduce the bug on the repo you linked in #423 with this fix, but it's already happening only intermittently without the fix, so it's not like that proves much ^^.

**Comment by matthieu-fesselier** [comment]
It does not, but I actually found the cause of the bug on our side. 

We have a component with a `auto-login` feature, which is supposed to redirect you at your IDP as soon as the page is loaded, if you are not authenticated. 

It seems that, when the bug appears, here is what is happening:
- page loaded
- `handleIncomingRedirect` called
- when resolved, `sessionInfo.isLoggedIn` is `false` -> we call the `login`
- after this, solid-authn-client-js performs the first redirect

When I deactivate the `auto-login` feature, everything works fine. 
Is there something that I can wait to be sure that the lib has completely handled the redirections?

**Comment by NSeydoux** [comment]
All the redirection handling happens in `handleIncomingRedirect`, so when it returns, no additional redirection occurs without being explicitly triggered (e.g. by calling `login`). Therefore, the steps you just described should work fine, and after having installed, built and served https://git.startinblox.com/framework/sib-auth/tree/feature/solid-client-authn-js, I can log in just fine, even when setting the `auto-login`, so it looks like the underlying issue is still unresolved. 

I think https://github.com/inrupt/solid-client-authn-js/pull/1243/commits/b411eecb1309e33f38f9bf9c5193444709a252f3 should resolve the issue. What I think was happening is the following: `handleIncomingRedirect` resolved before the silent authentication actually happened, and returned a (legitimately) logged out session. The `auto-login` component then called `login`, while the silent login triggered by `handleIncomingRedirect` was still pending. This created a race condition on the storage, and depending on which login got executed first the outcome was the issue you were having or the expected behaviour. Ca you retry with `auto-login` enabled and the new version of `@inrupt/solid-client-authn-browser@fixstore-race-condition` ?

**Comment by matthieu-fesselier** [comment]
Indeed you're right, and it now works perfectly, thanks a lot @NSeydoux !
