### ISSUE TITLE
Invalid refresh credentials even on first login

### ISSUE THREAD

**Issue by CayenneLow** [inrupt/solid-client-authn-js#1450]
### Search terms you've used

login
invalid_grant
refresh_token
DPoP binding

### Impacted package

Which packages do you think might be impacted by the bug ?

- [ ] solid-client-authn-browser
- [x] solid-client-authn-node
- [ ] solid-client-authn-core
- [ ] oidc-client-ext
- [ ] Other (please specify): ...

### Bug description
**Note: I am aware of Issue #1285 , however, this is happening even on the first login. I have also applied @NSeydoux 's workaround mentioned in Issue #1285 with no luck.**

After retrieving login details via ```@inrupt/generate-oidc-token```, I am unable to login when calling `session.login(<creds>)`, instead I receive an `Invalid refresh credentials` error that I didn't used to receive.

### To Reproduce
1. Run `@inrupt/generate-oidc-token` to get credentials
2. Call  `session.login(<creds>)`

### Expected result
For `session.login()` to return a logged in Session

### Actual result
```
(node:20940) DraftWarning: The DPoP APIs implements an IETF draft. Breaking draft implementations are included as minor versions of the openid-client library, therefore, the ~ semver operator should be used and close attention be payed to library changelog as well as the drafts themselves.
(Use `node --trace-warnings ...` to show where the warning was created)
Error: Invalid refresh credentials: OPError: invalid_grant (Invalid DPoP binding for refresh_token)
    at refreshAccess (D:\UNSW\Thesis\solidapp\node_modules\@inrupt\solid-client-authn-node\dist\login\oidc\oidcHandlers\RefreshTokenOidcHandler.js:49:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async RefreshTokenOidcHandler.handle (D:\UNSW\Thesis\solidapp\node_modules\@inrupt\solid-client-authn-node\dist\login\oidc\oidcHandlers\RefreshTokenOidcHandler.js:80:28)
    at async ClientAuthentication.login (D:\UNSW\Thesis\solidapp\node_modules\@inrupt\solid-client-authn-node\dist\ClientAuthentication.js:26:33)
    at async Session.login (D:\UNSW\Thesis\solidapp\node_modules\@inrupt\solid-client-authn-node\dist\Session.js:15:31)
    at async D:\UNSW\Thesis\solidapp\src\test.js:7:5
```

### Environment
```
  System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 16.98 GB / 31.93 GB
  Binaries:
    Node: 14.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.6.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1023.0), Chromium (91.0.864.48)
    Internet Explorer: 11.0.19041.1
  npmPackages:
    @fast-csv/parse: ^4.3.6 => 4.3.6
    @inrupt/generate-oidc-token: ^0.1.2 => 0.1.2
    @inrupt/solid-client: ^1.8.1 => 1.8.1
    @inrupt/solid-client-authn-node: ^1.8.1 => 1.8.1
    @inrupt/vocab-common-rdf: ^0.7.4 => 0.7.4
    awesome-typescript-loader: ^5.2.1 => 5.2.1
    moment: ^2.29.1 => 2.29.1
    parcel-bundler: ^1.12.5 => 1.12.5
    rdflib: ^2.2.3 => 2.2.3
    source-map-loader: ^3.0.0 => 3.0.0
    ts-node: ^10.0.0 => 10.0.0
    typescript: ^3.9.9 => 3.9.9
  npmGlobalPackages:
    expo-cli: 4.3.4
    ghost-cli: 1.15.3
    npm: 7.6.2
    typescript: 4.2.3
    vsc-leetcode-cli: 2.7.0
    windows-build-tools: 5.2.2
    yarn: 1.22.10
```

## Additional information
Used to work the last time I ran it a few hours ago with version 1.8.1, accounting for a new refresh token by using the `onNewRefreshToken` callback

**Comment by Vinnl** [comment]
Hi @CayenneLow, would you mind sharing what server you were trying to log in to, and maybe the exact parameters you are passing in `<creds>`? (No need to pass the values, just something like `clientId, clientSecret` should suffice.) That might help investigation.

**Comment by CayenneLow** [comment]
Hey @Vinnl !

Server I was logging into: https://broker.pod.inrupt.com/

Creds object:
```typescript
    const creds: ILoginInputOptions = {
        "refreshToken": refreshToken,
        "clientId": clientId",
        "clientSecret": clientSecret,
        "oidcIssuer": "https://broker.pod.inrupt.com/",
    }
```

^ These values were obtained via `@inrupt/generate-oidc-token`

**Comment by Vinnl** [comment]
Thanks @CayenneLow. You say that those values were obtained using `@inrupt/generate-oidc-token`, but in your first post you also mentioned "accounting for a new refresh token by using the onNewRefreshToken callback" - just to make sure, the `refreshToken` you passed was the one obtained from that callback, not from `@inrupt/generate-oidc-token`, is that right?

**Comment by CayenneLow** [comment]
Yes, my current set up is as such (reading the refresh token from a file):

```typescript
    const session = new Session({
        onNewRefreshToken: (newToken) => {
            writeFileSync(REFRESH_TOKEN_FILEPATH, newToken);
        },
    },
        "my-session");

   const refreshToken = readFileSync(REFRESH_TOKEN_FILEPATH).toString();
   const creds: ILoginInputOptions = {
        "refreshToken": refreshToken,
        "clientId": clientId",
        "clientSecret": clientSecret,
        "oidcIssuer": "https://broker.pod.inrupt.com/",
    }
```

**Comment by Vinnl** [comment]
Thanks, I have managed to reproduce your issue against the same server, but not against https://solidcommunity.net. I have asked some people more familiar with the server for help; I'll report back if I have more information.

**Comment by Vinnl** [comment]
Hi @CayenneLow, I'm afraid I have somewhat unfortunate news. It appears that the server at pod.inrupt.com has been updated to now require an additional token when logging in — which means solid-client-authn and generate-oidc-token will need to be updated to allow you to do this. We'll keep this issue open until that is done; until then, I'm afraid you're limited to using other Pod servers like https://solidcommunity.net, https://solidweb.org or https://inrupt.net.

**Comment by Vinnl** [comment]
Hi @CayenneLow, good news: the change on pod.inrupt.com has been rolled back, so it should work for you again. It might be reintroduced at some point in the future, at which time our tooling will be updated as well, which might require some code changes on your side too. Until then, however, hopefully things should keep working for you.

**Comment by CayenneLow** [comment]
Perfect, thanks a lot for all the help @Vinnl
