### ISSUE TITLE
403 Forbidden with saveSolidDatasetAt()

### ISSUE THREAD

**Issue by CayenneLow** [inrupt/solid-client-authn-js#1467]
### Search terms you've used
403
saveSolidDataset
Forbidden

### Impacted package

Which packages do you think might be impacted by the bug ?

- [ ] solid-client-authn-browser
- [x] solid-client-authn-node
- [ ] solid-client-authn-core
- [ ] oidc-client-ext
- [ ] Other (please specify): ...

### Bug description
Trying to save a solid dataset while logged in and I receive a 403 Forbidden error despite being logged in. I've tried creating a new account and generating new tokens via `@inrupt/generate-oidc-token` with no luck. I have also verified that a directory `/iot` does not exist at the time of this call. This used to work prior to the change cited in #1450. Apologies if this isn't the right place to post this.

My code snippet:

```typescript
import { createSolidDataset, createThing, saveSolidDatasetAt, setStringNoLocale, setThing } from "@inrupt/solid-client";
import { readFileSync, writeFileSync } from "fs";
import { ILoginInputOptions, Session } from "@inrupt/solid-client-authn-node";
import { RDF, REFRESH_TOKEN_FILEPATH } from "./constants";

(async function main() {
    // create solid dataset and insert Thing
    let dataset = createSolidDataset();
    let thing = createThing();
    thing = setStringNoLocale(thing, RDF + "Type", "Test");
    dataset = setThing(dataset, thing);

    // login
    const session = await login();
    if (session.info.isLoggedIn) {
        const url = "https://pod.inrupt.com/khye3/iot";
        // save data set
        try {
          dataset = await saveSolidDatasetAt(url, dataset, { fetch: session.fetch })
        } catch (error) {
            console.error(error);
        }
    } else {
        console.log("Not logged in!");
    }
})()

async function login() {
  const session = new Session({
      onNewRefreshToken: (newToken) => {
          writeFileSync(REFRESH_TOKEN_FILEPATH, newToken);
      },
  },
  "my-session");
  
  const refreshToken = readFileSync(REFRESH_TOKEN_FILEPATH).toString();
  const creds: ILoginInputOptions = {
      "refreshToken": refreshToken,
      "clientId": "CLIENT_ID",
      "clientSecret": "CLIENT_SECRET",
      "oidcIssuer": "https://broker.pod.inrupt.com/",
  }
  if (!session.info.isLoggedIn) {
      await session.login(creds);
  }
  return session;
}
```

### To Reproduce
1. Login with tokens generated via `@inrupt/generate-oidc-token`
2. Create dummy solid dataset
3. Call `saveSolidDatasetAt()` with created dataset

### Expected result
A message with a 2xx status code indicating success

### Actual result
```
The SolidDataset that was sent to the Pod is listed below.

# SolidDataset (no URL yet)

## Thing (no URL yet — identifier: `#162444717424416358224589005177`)

Property: http://www.w3.org/1999/02/22-rdf-syntax-ns#Type
- "Test" (string)

(1 new value added / 0 values removed)

    at Object.saveSolidDatasetAt (D:\UNSW\Thesis\solidapp\node_modules\@inrupt\solid-client\dist\index.js:2722:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  response: Response {
    size: 0,
    timeout: 0,
    [Symbol(Body internals)]: { body: [PassThrough], disturbed: false, error: null },
    [Symbol(Response internals)]: {
      url: 'https://pod.inrupt.com/khye3/iot',
      status: 403,
      statusText: 'Forbidden',
      headers: [Headers],
      counter: 0
    }
  }
}
```

### Environment
Please run

  npx envinfo --system --npmPackages --binaries --npmGlobalPackages --browsers

in your project folder and paste the output here:

```
  System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 17.23 GB / 31.93 GB
  Binaries:
    Node: 14.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.6.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1023.0), Chromium (91.0.864.54)      
    Internet Explorer: 11.0.19041.1
  npmPackages:
    @fast-csv/parse: ^4.3.6 => 4.3.6 
    @inrupt/generate-oidc-token: ^0.1.2 => 0.1.2 
    @inrupt/solid-client: ^1.9.0 => 1.9.0 
    @inrupt/solid-client-authn-node: ^1.9.0 => 1.9.0 
    @inrupt/vocab-common-rdf: ^0.7.4 => 0.7.4 
    awesome-typescript-loader: ^5.2.1 => 5.2.1 
    moment: ^2.29.1 => 2.29.1 
    parcel-bundler: ^1.12.5 => 1.12.5 
    rdflib: ^2.2.3 => 2.2.3 
    source-map-loader: ^3.0.0 => 3.0.0 
    ts-node: ^10.0.0 => 10.0.0 
    typescript: ^3.9.9 => 3.9.9 
  npmGlobalPackages:
    expo-cli: 4.3.4
    ghost-cli: 1.15.3
    npm: 7.6.2
    typescript: 4.2.3
    vsc-leetcode-cli: 2.7.0
    windows-build-tools: 5.2.2
    yarn: 1.22.10
```

**Comment by Vinnl** [comment]
Hi @CayenneLow, you might find this page helpful: https://docs.inrupt.com/developer-tools/javascript/client-libraries/reference/error-codes/#term-403-Forbidden

As it says, a 403 error usually means that the user that is currently authenticated does not have access to the given resource (in this case `https://pod.inrupt.com/khye3/iot`). Could you check the value of `session.info.webId`? Does the resource at `https://pod.inrupt.com/khye3/iot` already exist? If so, can you view and change it if you sign in to [Penny](https://penny.vincenttunru.com/) and look at that resource, and what the Access Control Resource (at https://pod.inrupt.com/khye3/iot?ext=acr) looks like? If not, could you share what the Access Control Resource of its Container looks like, i.e. https://pod.inrupt.com/khye3/?ext=acr?

**Comment by CayenneLow** [comment]
Hi @Vinnl, this is the value in `session.info.webId`: `https://pod.inrupt.com/khye3/profile/card#me`

The resource does not exist yet and I've verified that on Penny as well. My expectation was for it to be created (as mentioned [here](https://docs.inrupt.com/developer-tools/api/javascript/solid-client/modules/resource_soliddataset.html?highlight=turtle#savesoliddatasetat)). 

Also, I'm getting a 401 Unauthorized when trying to view the ACR of the container, despite being logged in.

**Comment by Vinnl** [comment]
OK, so if the resource doesn't exist yet, then the ACR of the container should apply, so that's where we're going to need to look. Do you get the 401 when you open it in Penny while logged in? Can you view the Container itself?

**Comment by CayenneLow** [comment]
No 401 errors when opening in Penny, I can see all resources stored within the Container.

**Comment by Vinnl** [comment]
OK, so 401 errors are usually returned when you're not authenticated - possibly you forgot to pass in the session's `fetch`?

Could you share [a screenshot](https://support.mozilla.org/en-US/kb/take-screenshots-firefox) of Penny that shows the Container's ACR?

**Comment by CayenneLow** [comment]
I viewed the ACR of the container in a browser, which gave me a 401 error as below:
![image](https://user-images.githubusercontent.com/39748879/123116110-fae44400-d483-11eb-9074-9eb8672d586d.png)

Here's the screenshot from Penny:
![image](https://user-images.githubusercontent.com/39748879/123115832-c07aa700-d483-11eb-8acf-fd459abf33cf.png)

**Comment by Vinnl** [comment]
Thanks @CayenneLow, but could you share a screenshot in Penny from the Container's ACR, i.e. what you get if you sign in [here](https://penny.vincenttunru.com/explore/?url=https%3A%2F%2Fpod.inrupt.com%2Fkhye3%2F%3Fext%3Dacr)? I want to see whether it has been changed to not give you access to add new resources to the container.

**Comment by CayenneLow** [comment]
Sorry, yes it seems like I don't have sufficient permissions. Where do I go from here?

![image](https://user-images.githubusercontent.com/39748879/123117385-0ab05800-d485-11eb-81ee-2daee195e603.png)

**Comment by Vinnl** [comment]
@CayenneLow You're not signed in there :) Could you press "Connect", then try again?

**Comment by CayenneLow** [comment]
Ah, sorry that's really embarassing. Sorry, totally new to all of this.

![image](https://user-images.githubusercontent.com/39748879/123119460-e81f3e80-d486-11eb-8103-fb50f860490c.png)

**Comment by Vinnl** [comment]
No problem, it's not super straightforward - but we're getting closer :) OK, so that doesn't look too weird, but could you show the Policies it refers to as well? So that's:

- https://pod.inrupt.com/khye3/pb_policies/.ttl.editors.ttl
- https://pod.inrupt.com/khye3/pb_policies/.ttl.viewers.ttl
- https://pod.inrupt.com/khye3/policies/

Could you share screenshots of those resources in Penny?

**Comment by CayenneLow** [comment]
Here they are, in order:
- ![image](https://user-images.githubusercontent.com/39748879/123123729-67624180-d48a-11eb-860c-fa9cf110069f.png)
- ![image](https://user-images.githubusercontent.com/39748879/123123800-78ab4e00-d48a-11eb-83eb-b7826a820421.png)
- ![image](https://user-images.githubusercontent.com/39748879/123124214-d3dd4080-d48a-11eb-9869-e6a5a2900f83.png)
![image](https://user-images.githubusercontent.com/39748879/123124283-e35c8980-d48a-11eb-9bc4-718497596835.png)
![image](https://user-images.githubusercontent.com/39748879/123124305-e9526a80-d48a-11eb-8a5e-f8b846dd56ff.png)
![image](https://user-images.githubusercontent.com/39748879/123124335-efe0e200-d48a-11eb-9b5b-826dacf30852.png)

**Comment by Vinnl** [comment]
Great, thanks! I have recreated all your access settings in my own Pod, and have been able to reproduce your issue. Now to find out what's going on...

**Comment by Vinnl** [comment]
Hi @CayenneLow, looks like it was an issue with pod.inrupt.com - you're on a roll finding those! :) I reported it there and they deployed a fix, which appears to have solved it for my reproduction. Could you confirm whether it now works for you too?

**Comment by CayenneLow** [comment]
Hey @Vinnl thanks again for all the help! It works on my end too :)

**Comment by Vinnl** [comment]
Great, thanks for reporting back!
