### ISSUE TITLE
Dynamic Client Registration should use subject_type public

### ISSUE THREAD

**Issue by matthieubosquet** [inrupt/solid-client-authn-js#1551]
### Search terms you've used

pairwise

### Impacted package

Which packages do you think might be impacted by the bug ?

- [x] solid-client-authn-browser
- [x] solid-client-authn-node
- [x] solid-client-authn-core

### Bug description

The `subject_type` in context of Solid OIDC should be `public` instead of `pairwise`. It doesn't make sense to have a pairwise `sub` claim in ID tokens when there is also a WebID claim there. Solid IdPs should not really support it and solid authentication clients should explicitly ask for public or potentially omit that parameter if the IdP has no `subject_types_supported` defined in its discovery document.

https://github.com/inrupt/solid-client-authn-js/blob/aeae280b053614a64fce6d1b841ddc920381d76b/packages/oidc/src/dcr/clientRegistrar.ts#L114-L123

See also: https://inrupt.net/.well-known/openid-configuration & https://openid.net/specs/openid-connect-core-1_0.html#SubjectIDTypes

**Comment by NSeydoux** [comment]
Well spotted, we should indeed fix this.
