### ISSUE TITLE
v1.10.0 incompletely released?

### ISSUE THREAD

**Issue by raboof** [inrupt/solid-client-authn-js#1554]
### Search terms you've used
v1.10.0

### Impacted package

Which packages do you think might be impacted by the bug ?

- [x] solid-client-authn-browser
- [ ] solid-client-authn-node
- [ ] solid-client-authn-core
- [x] oidc-client-ext
- [ ] Other (please specify): ...

### Bug description

I see solid-client-authn-browser v1.10.0 is on npmjs.org, but it depends on `@inrupt/oidc-client-ext@^1.10.0`, which isn't there.

https://www.npmjs.com/package/@inrupt/solid-client-authn-browser
https://www.npmjs.com/package/@inrupt/oidc-client-ext

Version 1.10.1-release-1075016947-7231-1627478414.0 *is* available for both, though.

**Comment by NSeydoux** [comment]
Thanks for reporting this ! There seems to be some issue with the latest release being made available on NPM. We are currently investigating this, but in the meantime you may want to use `v1.9.1` tag (`npm install @inrupt/solid-client-authn-browser@1.9.1`). I'll update this thread as the situation progresses.

**Comment by NSeydoux** [comment]
An error had silently made its way into the automatic release process, but it looks like manually running a release fixed it for now. We'll look at the deeper issue that prevented the release from happening properly, but it should sort out your issue on the short term. can you confirm, and we can close the issue ?

**Comment by raboof** [comment]
> can you confirm

Yes, I can confirm v1.10.0 is now available and works, thanks!
