### ISSUE TITLE
Logout followed by login fails

### ISSUE THREAD

**Issue by AJamesPhillips** [inrupt/solid-client-authn-js#1624]
### Search terms you've used
openid-configuration, logout, login

### Impacted package

Not sure:

- [x] solid-client-authn-browser ?
- [ ] ? solid-client-authn-node
- [ ] ? solid-client-authn-core
- [ ] ? oidc-client-ext

### Bug description
Using Brave or Chrome browsers with solid-client-authn-browser@1.11.0 .

If a user signs in, signs out, then signs in again the second and subsequent sign in attempts fail until the user refreshes their browser tab.

I suspect this is because I am re-using the same session object that comes from `getDefaultSession` (from `@inrupt/solid-client-authn-browser`).

To start the login I call `session.login({...})` where session comes from `getDefaultSession`.  This works successfully the first time but after calling `session.logout()`, the second time session.login is called an error occurs.  Looking in the logs it appears it is trying to fetch, and gets a 404 from: `https://<my user name>.solidcommunity.net/profile/card/.well-known/openid-configuration`, where as the first time session.login is called I think it goes to: `https://solidcommunity.net/.well-known/openid-configuration`

### Expected result
Should log the user back in.

### Actual result
Error.

![image](https://user-images.githubusercontent.com/526509/129939508-67420c35-3223-4ea7-afe4-349c177e5af7.png)

### Environment
```
$ npx envinfo --system --npmPackages --binaries --npmGlobalPackages --browsers

  npmPackages:
    @inrupt/solid-client: ^1.11.0 => 1.11.0 
    @inrupt/solid-client-authn-browser: ^1.11.0 => 1.11.0 
    @material-ui/core: 4.11.4 => 4.11.4 
    @material-ui/icons: 4.11.2 => 4.11.2 
    @material-ui/lab: 4.0.0-alpha.58 => 4.0.0-alpha.58 
    @prefresh/snowpack: 2.0.1 => 2.0.1 
    @snowpack/plugin-dotenv: 2.0.5 => 2.0.5 
    @snowpack/plugin-sass: 1.4.0 => 1.4.0 
    @snowpack/plugin-typescript: 1.1.1 => 1.1.1 
    @snowpack/web-test-runner-plugin: 0.1.5 => 0.1.5 
    @testing-library/preact: 2.0.0 => 2.0.0 
    @types/boom: 4.3.5 => 4.3.5 
    @types/chai: 4.2.14 => 4.2.14 
    @types/graphlib: 2.1.7 => 2.1.7 
    @types/localforage: ^0.0.34 => 0.0.34 
    @types/luxon: 1.26.3 => 1.26.3 
    @types/markdown-to-jsx: 6.11.3 => 6.11.3 
    @types/react-redux: 7.1.12 => 7.1.12 
    @web/test-runner: 0.10.0 => 0.10.0 
    chai: 4.2.0 => 4.2.0 
    fuzzysort: 1.1.4 => 1.1.4 
    graphlib: 2.1.8 => 2.1.8 
    localforage: ^1.9.0 => 1.9.0 
    luxon: 1.26.0 => 1.26.0 
    markdown-to-jsx: 7.1.1 => 7.1.1 
    preact: 10.5.7 => 10.5.7 
    prettier: ^2.0.5 => 2.0.5 
    react-redux: 7.2.2 => 7.2.2 
    snowpack: 3.8.3 => 3.8.3 
    typescript: 4.2.4 => 4.2.4 
  npmGlobalPackages:
    npm: 6.14.8
    yarn: 1.22.10
```

**Comment by NSeydoux** [comment]
I'm glad you figured it out :)
