### ISSUE TITLE
jest jsdom: ReferenceError: TextEncoder is not defined

### ISSUE THREAD

**Issue by angelo-v** [inrupt/solid-client-authn-js#1676]
### Search terms you've used
jsdom, TextEncoder

### Impacted package

Which packages do you think might be impacted by the bug ?

- [x] solid-client-authn-browser
- [ ] solid-client-authn-node
- [ ] solid-client-authn-core
- [ ] oidc-client-ext
- [ ] Other (please specify): ...

### Bug description

importing from `@inrupt/solid-client-authn-browser` fails in a jest test using jsdom environment:

```
Test suite failed to run

    ReferenceError: TextEncoder is not defined

      3 |  */
      4 |
    > 5 | import { login } from '@inrupt/solid-client-authn-browser';
        | ^
      6 |
      7 | describe('test', () => {
      8 |   it('should work', () => {
```

### To Reproduce

Run this test:

```typescript
/**
 * @jest-environment jsdom
 */

import { login } from '@inrupt/solid-client-authn-browser';

describe('test', () => {
  it('should work', () => {
    expect(login).toBeDefined();
  });
});
```

### Expected result

Test runs successfully

### Actual result

ReferenceError: TextEncoder is not defined

### Environment

```
 @inrupt/solid-client-authn-browser: ^1.11.2 => 1.11.2
```

## Additional information

- The problem did not occur with @inrupt/solid-client-authn-browser 1.6.1
- It works fine with  `@jest-environment node`

**Comment by angelo-v** [comment]
A workarround (or solution?) is to polyfill TextEncoder and TextDecoder in a setupFilesAfterEnv script:

```typescript
import { TextEncoder, TextDecoder } from 'util';
global.TextEncoder = TextEncoder;
global.TextDecoder = TextDecoder;
```

**Comment by NSeydoux** [comment]
Hi @angelo-v ! I think this issue unfortunately goes beyond the scope of `@inrupt/solid-client-authn-browser`, and we have to work around it ourselves: `jose` expects `TextEncoder` to be present in the environment, but `jsdom` does not put it there (see https://github.com/jsdom/jsdom/issues/2524). Our solution (suggested somewhere in the linked issue) is to use a custom Jest environment: https://github.com/inrupt/solid-client-authn-js/blob/main/tests/environment/customEnvironment.js, referenced e.g. in https://github.com/inrupt/solid-client-authn-js/blob/main/packages/browser/jest.config.js.

**Comment by angelo-v** [comment]
Thanks, I understand that. Using setupFilesAfterEnv works as well and is more lightweight then creating a custom jest env imo. Perhaps you can at least add a hint to the documentation about that, because usually people just using the inrupt lib do not know about jose and those internals, they just wonder why the inrupt lib causes an error in the tests

**Comment by nhhockeyplayer** [comment]
import statements should remain unhindered... 
this is a blatant flank to typescript language in the field 
It all brings development to a halt
this is the kind of stuff open source needs to stop doing

and the issues mount
https://github.com/thymikee/jest-preset-angular/issues/1697

if you have a release that does not do this consider rolling everything back to that and start over

if it dont work and its released roll it back and start over

**Comment by CalebJamesStevens** [comment]
Still an issue today. Jest 29, added the util script

**Comment by hjohnsick** [comment]
> A workarround (or solution?) is to polyfill TextEncoder and TextDecoder in a setupFilesAfterEnv script:
> 
> ```ts
> import { TextEncoder, TextDecoder } from 'util';
> global.TextEncoder = TextEncoder;
> global.TextDecoder = TextDecoder;
> ```

How exactly do I add this to a setupFilesAfterEnv script?  I am using typescript and I have a jest-config.d.ts and it has this inside,  `declare const root: any;
export { root as rootDir };
export declare const setupFilesAfterEnv: string[];
export declare const testMatch: string[];
export declare const testPathIgnorePatterns: string[];
export declare const coveragePathIgnorePatterns: string[];
export declare const coverageDirectory: string;
`

**Comment by ThisIsMissEm** [comment]
We actually have a bit of an update here: we've just released a package that helps by polyfilling the required Web APIs: https://www.npmjs.com/package/@inrupt/jest-jsdom-polyfills

It's still being rolled out across the SDK repos, but in our testing so far it should provide everything needed. We're aware that there may be an issue with UInt8Arrays, and that's due to an underlying jsdom issue: https://github.com/jsdom/whatwg-encoding/pull/13

**Comment by ThisIsMissEm** [comment]
@hjohnsick you can see an example here: https://github.com/inrupt/solid-client-access-grants-js/pull/366/files

You should likely have a `jest.config.ts` file in your repo, unless you're somehow using jest without any configuration at all (which I've only rarely seen)

**Comment by ThisIsMissEm** [comment]
> Thanks, I understand that. Using setupFilesAfterEnv works as well and is more lightweight then creating a custom jest env imo. Perhaps you can at least add a hint to the documentation about that, because usually people just using the inrupt lib do not know about jose and those internals, they just wonder why the inrupt lib causes an error in the tests

Yup, we agree, we've since moved from custom environments to setupFilesAfterEnv

**Comment by allestaire** [comment]
Seems like the answers didnt state where to put the said code.

**Comment by NSeydoux** [comment]
You can use this repository as an example: see https://github.com/inrupt/solid-client-authn-js/blob/main/jest.setup.ts, where the polyfills are imported, and https://github.com/inrupt/solid-client-authn-js/blob/72cd3486efd627d01c8f272a502639075cf16c7c/jest.config.ts#L39, where jest is configured to pick up this setup.

**Comment by clarkeustaquio** [comment]
Only solution worked to me is to add this line of code to `src/setupTests.ts`

```
import '@testing-library/jest-dom';
import { TextEncoder } from 'util';

global.TextEncoder = TextEncoder;
```

**Comment by ThisIsMissEm** [comment]
> Only solution worked to me is to add this line of code to `src/setupTests.ts`
> 
> ```
> import '@testing-library/jest-dom';
> import { TextEncoder } from 'util';
> 
> global.TextEncoder = TextEncoder;
> ```

It's strange you needed that as we do that polyfill of textencoder in our polyfill.. I can't comment on testing lib & jest-dom though. If you've a repo to share I'd love to run a few experiments to check our package is working as expected

**Comment by danielbakas** [comment]
Problem still present. Adding this to setupTests.js still works:

```js
import { TextEncoder } from 'util';

global.TextEncoder = TextEncoder;
```

**Comment by jeswr** [comment]
Closing this issue as it is an error in Jest with a workaround (i.e. https://github.com/inrupt/solid-client-authn-js/issues/1676#issuecomment-1617024437)

**Comment by vojdan** [comment]
> Only solution worked to me is to add this line of code to `src/setupTests.ts`
> 
> ```
> import '@testing-library/jest-dom';
> import { TextEncoder } from 'util';
> 
> global.TextEncoder = TextEncoder;
> ```

This worked for me when using CRA.

**Comment by BowaDAO** [comment]
This did not work for me. Still getting '
    ReferenceError: TextEncoder is not defined'

**Comment by NSeydoux** [comment]
@BowaDAO can you describe your setup a bit more so that I would be able to help?

@Alfredoeb9 thanks for providing something that works around the issue in your case. Can you elaborate a bit more on your setup as well, so that I may figure out why the solution we use for ourselves now doesn't cover your use case?

**Comment by BowaDAO** [comment]
I've been able to resolve the issue.

**Comment by christopher-theagen** [comment]
`.jest/setup.js`
```js
import { TextEncoder, TextDecoder } from 'util';

global.TextEncoder = TextEncoder;
global.TextDecoder = TextDecoder;
```

**Comment by shaktish** [comment]
how does this import from **util**, work ? do i need to install any dependency ?

**Comment by Milan-960** [comment]
I am also having the same issue and it does not help me to resolve that. :(

**Comment by ssp7** [comment]
I just updated my react app to node 20 from 16. I am still having this issue. Also, my react builds using cra through craco. Any suggestions? I have tried assigning TextEncoder/Decoder as some workaround suggests but still getting that reference error. What am I missing?

**Comment by NSeydoux** [comment]
In our other projects, we use a library that polyfills all these gaps between JSDom and the actual browser environment. It shouldn't be different to manually specifying the `TextEncoder` and `TextDecoder` as described in this issue though. Are you using the latest version of the library?

Here is an example of our polyfill setup: https://github.com/inrupt/solid-client-js/blob/main/jest.setup.ts, then consumed in https://github.com/inrupt/solid-client-js/blob/daa08001fd71c0fdf9ef482dc0e345aab3734d7d/jest.config.ts#L27.
