### ISSUE TITLE
import fails with esbuild

### ISSUE THREAD

**Issue by janKollars** [inrupt/solid-client-authn-js#1815]
### Search terms you've used

- esbuild
- vite
- does not provide an export named
- esm

### Impacted package

Which packages do you think might be impacted by the bug ?

- [x] solid-client-authn-browser
- [ ] solid-client-authn-node
- [ ] solid-client-authn-core
- [ ] oidc-client-ext
- [ ] Other (please specify): ...

### Bug description

`solid-client-authn-browser` appears to be not working with Vite when it is running esbuild. The build mode which is using Webpack works.

### To Reproduce
1. create Vite project and run the dev server: `npm init vite@latest`, `npm install` and `npm run dev`
2. add the following code to the `<script>` section of the file `App.vue`
```js
import { ref } from 'Vue'
import { Session } from "@inrupt/solid-client-authn-browser"
const test = ref('')
console.log(new Session())
```

### Expected result

Session is imported and can be used.

### Actual result

Error in browser console
```
Uncaught SyntaxError: The requested module '/node_modules/@inrupt/solid-client-authn-browser/dist/index.js?t=1638734365925' does not provide an export named 'Session'
```

### Environment

```
System:
    OS: macOS 12.0.1
    CPU: x64 Intel(R) Core(TM)
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.2.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.4 - /usr/local/bin/npm
  npmPackages:
    @inrupt/solid-client-authn-browser: ^1.11.2 => 1.11.2 
    @vitejs/plugin-vue: ^1.9.3 => 1.10.1 
    vite: ^2.6.4 => 2.6.14 
    vue: ^3.2.23 => 3.2.23 
  npmGlobalPackages:
    npm: 8.1.4
```

## Additional information

I believe the problem is that no esm version is shipped by the `solid-client-authn-browser`.

**Comment by janKollars** [comment]
Adding the compiler option `"module": "ES6"` to the packages' `tsconfig.json` seems to result in the correct output. It also fixes the problem described above on my local setup.

However, I am not sure what the best practice is for configuring the tsconfig or for shipping a project like yours which strives to be flexible and compatible with various environments and build systems.

**Comment by rimmartin** [comment]
Following example: https://docs.inrupt.com/developer-tools/javascript/client-libraries/tutorial/authenticate-browser/

I see similar "does not provide an export named" for fetch & getDefaultSession from line

```
import { handleIncomingRedirect, login, fetch, getDefaultSession } from './js/solid-client-authn-browser/solid-client-authn.bundle.js'
```

Put "module": "ES6" in every compiler option in every tsconfig.json I could find clone of main branch.

Running from cypress choosing Electron 94 & Firefox 95.  No satisfying success yet

**Comment by rimmartin** [comment]
However
```
import { handleIncomingRedirect, login, fetch, getDefaultSession } from './js/solid-client-authn-browser/index.browser.js'
```
succeeded!
