### ISSUE TITLE
fragment identifier in openid-configuration URL?

### ISSUE THREAD

**Issue by michielbdejong** [inrupt/solid-client-authn-js#186]
I'm running latest master and seeing it retrieve
https://michielbdejong.inrupt.net/.well-known/openid-configuration#me
Shouldn't that be
https://michielbdejong.inrupt.net/.well-known/openid-configuration
instead?

**Comment by NSeydoux** [comment]
Could not reproduce as of version `0.2.2`. Could you give it another try ?

**Comment by michielbdejong** [comment]
ok, thanks!
