### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by svrstich** [inrupt/solid-client-authn-js#1924]
Hi all,
I'm having an issue installing this library. 

Executing:
> git clone https://github.com/inrupt/solid-client-authn-js.git
> cd solid-client-authn-js
> npm install

generates following output:

> root@ postinstall C:\<masked>\community-server\solid-client-authn-js
> lerna bootstrap --ci && npm run build
>lerna notice cli v4.0.0
>lerna info ci enabled
>lerna info Bootstrapping 4 packages
>lerna info Symlinking packages and binaries
>lerna success Bootstrapped 4 packages
> root@ build C:\<masked>\community-server\solid-client-authn-js
> lerna run build
>lerna notice cli v4.0.0
>lerna info Executing command in 4 packages: "npm run build"
>lerna ERR! npm run build exited 2 in '@inrupt/solid-client-authn-core'
>lerna ERR! npm run build stdout:
> @inrupt/solid-client-authn-core@1.11.3 build C:\<masked>\community-server\solid-client-authn-js\packages\core
> tsc -p tsconfig.json
>../../../node_modules/@types/express-serve-static-core/index.d.ts(589,18): error TS2430: Interface 'Response<ResBody, Locals, >StatusCode>' incorrectly extends interface 'ServerResponse'.
> Types of property 'req' are incompatible.
>    Type 'Request<ParamsDictionary, any, any, ParsedQs, Record<string, any>> | undefined' is not assignable to type 'IncomingMessage'.
>      Type 'undefined' is not assignable to type 'IncomingMessage'.
> ../../../node_modules/@types/express/index.d.ts(58,55): error TS2344: Type 'Response<any, Record<string, any>>' does not satisfy the constraint 'ServerResponse'.
>  Types of property 'req' are incompatible.
>    Type 'Request<ParamsDictionary, any, any, ParsedQs, Record<string, any>> | undefined' is not assignable to type 'IncomingMessage'.
>      Type 'undefined' is not assignable to type 'IncomingMessage'.
>lerna ERR! npm run build stderr:
>npm ERR! code ELIFECYCLE
>npm ERR! errno 2
>npm ERR! @inrupt/solid-client-authn-core@1.11.3 build: `tsc -p tsconfig.json`
>npm ERR! Exit status 2
>npm ERR!
>npm ERR! Failed at the @inrupt/solid-client-authn-core@1.11.3 build script.
>npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
>npm ERR! A complete log of this run can be found in:
>npm ERR!     C:\<masked>
>lerna ERR! npm run build exited 2 in '@inrupt/solid-client-authn-core'
>npm ERR! code ELIFECYCLE
>npm ERR! errno 2
>npm ERR! root@ build: `lerna run build`
>npm ERR! Exit status 2
>npm ERR!
>npm ERR! Failed at the root@ build script.
>npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
>npm ERR! A complete log of this run can be found in:
>npm ERR!     C:\<masked>
>npm ERR! code ELIFECYCLE
>npm ERR! errno 2
>npm ERR! root@ postinstall: `lerna bootstrap --ci && npm run build`
>npm ERR! Exit status 2
>npm ERR!
>npm ERR! Failed at the root@ postinstall script.
>npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
>npm ERR! A complete log of this run can be found in:
>npm ERR!     C:\<masked>`

Any clues?

Regards,
Stijn

PS: Some more info

>60 silly lifecycle root@~postinstall: Returned: code: 2  signal: null
>61 info lifecycle root@~postinstall: Failed to exec postinstall script
>62 verbose stack Error: root@ postinstall: `lerna bootstrap --ci && npm run build`
>62 verbose stack Exit status 2
>62 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
>62 verbose stack     at EventEmitter.emit (events.js:400:28)
>62 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
>62 verbose stack     at ChildProcess.emit (events.js:400:28)
>62 verbose stack     at maybeClose (internal/child_process.js:1058:16)
>62 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
>63 verbose pkgid root@
>64 verbose cwd C:\<masked>\community-server\solid-client-authn-js
>65 verbose Windows_NT 10.0.19044
>66 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
>67 verbose node v14.18.1
>68 verbose npm  v6.14.15
>69 error code ELIFECYCLE
>70 error errno 2
>71 error root@ postinstall: `lerna bootstrap --ci && npm run build`
>71 error Exit status 2
>72 error Failed at the root@ postinstall script.
>72 error This is probably not a problem with npm. There is likely additional logging output above.
>73 verbose exit [ 2, true ]`

**Comment by georgepacheco** [comment]
Hi @svrstich, 

I'm having the same issue. Did you find out a solution?

Regards.

**Comment by svrstich** [comment]
Hi @georgepacheco,

I moved to a linux (Ubuntu) deployment, and checked whether all necessary version dependencies are met.

Stijn

**Comment by georgepacheco** [comment]
Thanks @svrstich. I'll try it.

**Comment by NSeydoux** [comment]
I'm so sorry, I completely missed this issue being opened. Is it still relevant, are you still experiencing the problem ? Could you specify your OS and the Node/NPM version you are using ?
