### ISSUE TITLE
Client should not use solid_oidc_supported to discover Solid-OIDC support

### ISSUE THREAD

**Issue by joachimvh** [inrupt/solid-client-authn-js#1927]
### Search terms you've used
solid_oidc_supported

### Impacted package

Which packages do you think might be impacted by the bug ?

- [ ] solid-client-authn-browser
- [ ] solid-client-authn-node
- [x] solid-client-authn-core
- [ ] oidc-client-ext
- [ ] Other (please specify): ...

### Bug description
The server checks if an IdP has the `solid_oidc_supported` value set to discover if a server supports Solid-OIDC. This is no longer the correct way to discover such server, see the spec at https://solid.github.io/solid-oidc/#discovery and related comment https://github.com/solid/community-server/pull/1040#pullrequestreview-795258378 (which is how I discovered it).

The client should now check if `webid` is one of the supported scopes.

https://github.com/inrupt/solid-client-authn-js/blob/93ac2d482a2053baa384484c18fdbff245af3e6c/packages/core/src/login/oidc/IClientRegistrar.ts#L79-L85

**Comment by NSeydoux** [comment]
Thanks for reporting this @joachimvh , it is indeed a known issue. I'll get a fix in soon.

**Comment by NSeydoux** [comment]
`v1.11.4` is being released, and it should contain the fix for this. Please let me know if the issue persists, and sorry it took this long !
