### ISSUE TITLE
Code break in v1.11.5

### ISSUE THREAD

**Issue by IshaanOhri** [inrupt/solid-client-authn-js#1991]
### Impacted package

Which packages do you think might be impacted by the bug ?

- [ ] solid-client-authn-browser
- [ ] solid-client-authn-core
- [ ] oidc-client-ext

### Bug description
The login process doesn't redirect to Inrupt's OAuth page. It throws an error.

### To Reproduce
1. Clone my git repo (`https://github.com/IshaanOhri/pod-nextjs.git`) on commit `ce198a88ffe3b1ee1c44c2da1145af68713e080d` where I have a basic code implementing the login functionality

### Expected result
The Inrupt's OAuth page should open up where I can enter my credentials

### Actual result
Following error occurs:

![image](https://user-images.githubusercontent.com/39885197/155282554-cf996724-2241-4e20-976d-79f2eb3ca8d6.png)

## Additional information
The code works perfectly fine on v1.11.3

**Comment by jeff-zucker** [comment]
I am not sure this is the same issue but the dead-simple page below works against solidcommunity.net in 1.11.3 but produces this error in `1.11.5
```
solid-client-authn.bundle.js:2 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'includes')
    at solid-client-authn.bundle.js:2:47779
    at t.handleRegistration (solid-client-authn.bundle.js:2:47865)
    at t.default.handle (solid-client-authn.bundle.js:2:20696)
    at async t.default.login (solid-client-authn.bundle.js:2:6519)
    at async login (solid-client-authn.bundle.js:2:8394)
(anonymous) @ solid-client-authn.bundle.js:2
t.handleRegistration @ solid-client-authn.bundle.js:2
handle @ solid-client-authn.bundle.js:2
await in handle (async)
t.login @ solid-client-authn.bundle.js:2
loginButton.onclick @ a.html:17
```
Here's the page : 
```html
<span id="webId"></span>
<input id="oidc" value="https://solidcommunity.net" style="width:24em" />
<button id="loginButton">Login</button>
<button id="logoutButton">Logout</button>

<script src="https://cdn.jsdelivr.net/npm/@inrupt/solid-client-authn-browser@1.11.5/dist/solid-client-authn.bundle.js"></script>

<script>

const iscan = solidClientAuthentication;
var session = iscan.getDefaultSession();

const loginButton = document.querySelector("#loginButton");
const logoutButton = document.querySelector("#logoutButton");
const webIdArea = document.querySelector("#webId");
loginButton.onclick = ()=> { 
  return iscan.login({
    oidcIssuer: document.getElementById("oidc").value,
    redirectUrl: window.location.href,
    clientName: "Minimal login/logout"
  });
};
logoutButton.onclick = async ()=> { 
  await session.logout();
  showLoginStatus();
};
async function handleRedirectAfterLogin() {
  await iscan.handleIncomingRedirect();
  showLoginStatus();
}
function showLoginStatus() {
  session = iscan.getDefaultSession();
  if (session.info.isLoggedIn) {
    loginButton.style.display = "none";
    logoutButton.style.display = "inline-block";
    webId.innerHTML = `Logged in as ${session.info.webId}`;
  }
  else {
    loginButton.style.display =  "inline-block";
    logoutButton.style.display = "none";
    webId.innerHTML = `Not logged in.`;
  }
}
handleRedirectAfterLogin();
</script></body></html>
```

**Comment by IshaanOhri** [comment]
@jeff-zucker I get exactly the same error.

**Comment by theRealImy** [comment]
I can also reproduce this in SolidOS if lib version is set on 1.11.5

**Comment by theRealImy** [comment]
@IshaanOhri we managed to play a hot fix on the publicly available NSS servers (inrupt.net, solidcommunity.net, solidweb.org) so you will not encounter the issue right anymore.

**Comment by IshaanOhri** [comment]
For the time being I have rolled back my package version to `1.11.3`, which works perfectly for me. But still waiting for a resolution from Inrupt's side

**Comment by NSeydoux** [comment]
Thanks to @theRealImy and @ThisIsMissEm for mitigating the issue on public NSS instances. #2000 should fix the issue at our browser library level, which is where the bug was located. I'll update this issue when it is released.

**Comment by NSeydoux** [comment]
`v1.11.6` of solid-client-authn was just released, and should resolve the issue. Please do reopen if the problem persists, in particular on private NSS instances.
