### ISSUE TITLE
Installing with node 18 fails with "npm ERR! engine Not compatible with your version of node/npm: @inrupt/solid-client-authn-browser@1.12.2"

### ISSUE THREAD

**Issue by hexagon6** [inrupt/solid-client-authn-js#2374]
### Search terms you've used

node 18

### Impacted package

Which packages do you think might be impacted by the bug ?

- [x] solid-client-authn-browser
- [x] solid-client-authn-node
- [x] solid-client-authn-core
- [x] oidc-client-ext
- [ ] Other (please specify): ...

### Bug description

Node 18 is not supported

### To Reproduce
1. load node 18 into environment e.g. with `nvm use 18`
2. run `npm install @inrupt/solid-client-authn-browser`

### Expected result

Installation successful.

### Actual result

```bash
$ npm install @inrupt/solid-client-authn-browser
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: @inrupt/solid-client-authn-browser@1.12.2
npm ERR! notsup Not compatible with your version of node/npm: @inrupt/solid-client-authn-browser@1.12.2
npm ERR! notsup Required: {"node":"^14.0.0 || ^16.0.0"}
npm ERR! notsup Actual:   {"npm":"8.19.2","node":"v18.10.0"}
```

### Environment
Please run

  npx envinfo --system --npmPackages --binaries --npmGlobalPackages --browsers

in your project folder and paste the output here:

```
$ npx envinfo --system --npmPackages --binaries --npmGlobalPackages --browsers
 System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (16) x64 AMD Ryzen 7 PRO 5850U with Radeon Graphics
    Memory: 25.19 GB / 30.19 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.10.0 - ~/.nvm/versions/node/v18.10.0/bin/node
    npm: 8.19.2 - ~/.nvm/versions/node/v18.10.0/bin/npm
  Browsers:
    Brave Browser: 105.1.43.89
    Firefox: 105.0.3
  npmPackages:
    @fontsource/fira-mono: ^4.5.0 => 4.5.10 
    @neoconfetti/svelte: ^1.0.0 => 1.0.0 
    @playwright/test: ^1.25.0 => 1.27.0 
    @sveltejs/adapter-auto: next => 1.0.0-next.80 
    @sveltejs/kit: next => 1.0.0-next.511 
    @types/cookie: ^0.5.1 => 0.5.1 
    eslint: ^8.16.0 => 8.25.0 
    eslint-config-prettier: ^8.3.0 => 8.5.0 
    eslint-plugin-svelte3: ^4.0.0 => 4.0.0 
    prettier: ^2.6.2 => 2.7.1 
    prettier-plugin-svelte: ^2.7.0 => 2.8.0 
    svelte: ^3.46.0 => 3.50.1 
    svelte-check: ^2.7.1 => 2.9.1 
    typescript: ^4.7.4 => 4.8.4 
    vite: ^3.1.0 => 3.1.7 
  npmGlobalPackages:
    corepack: 0.14.1
    npm: 8.19.2
```

**Comment by NSeydoux** [comment]
Thanks for reaching out! Node 18 is not supported yet, which is why the `package.json` has the `engine` field setup the way it currently is. We are working on adding support for Node18, I'll update this issue as we progress.

**Comment by ThisIsMissEm** [comment]
Just to clarify, this is due to Node.js 18 shipping a native `fetch` implementation, which can cause issues with out fetch implementation, we're working on a way to resolve this, but it's a pretty big chunk of work.

**Comment by hexagon6** [comment]
Also having to run the test runner with `NODE_OPTIONS=--experimental-vm-modules npm run test`

**Comment by hexagon6** [comment]
Interestingly: when running `npm test` on solid-client-authn-js it works on node@18.8.0.

```bash
 PASS   node  packages/node/src/login/oidc/oidcHandlers/AuthorizationCodeWithPkceOidcHandler.spec.ts (8.352 s)
  AuthorizationCodeWithPkceOidcHandler
    canHandle
      ✓ should accept a configuration with many grant types including authorization code (2 ms)
      ✓ should accept a configuration with only the authorization code grant type
      ✓ shouldn't accept a configuration that has many grant types not including authorization code (1 ms)
      ✓ shouldn't accept a configuration that does not include grant types
    handle
      ✓ redirects the user to the specified IdP (6 ms)
      ✓ sets the specified options in the query params (2 ms)
      ✓ saves relevant information in storage (2 ms)
      ✓ serializes the token type boolean appropriately (1 ms)

----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------|---------|----------|---------|---------|-------------------
All files |       0 |        0 |       0 |       0 |                   
----------|---------|----------|---------|---------|-------------------
Test Suites: 58 passed, 58 total
Tests:       3 skipped, 2 todo, 482 passed, 487 total
Snapshots:   0 total
Time:        101.999 s
Ran all test suites in 4 projects.

solid-client-authn-js$ node --version
v18.8.0
```

**Comment by ThisIsMissEm** [comment]
@hexagon6 hi, thanks, we're aware of these issues, and how things are currently compatible or not. Unfortunately the work on node.js 18 support was delayed by an overhaul of our end-to-end testing infrastructure, which is now nearing completion.

**Comment by ThisIsMissEm** [comment]
@hexagon6 oh, also that `--experimental-vm-modules` is due to you upgrade `json-ld` — it's switched to being a ESM-only module, which means Jest doesn't really like it, as Jest doesn't fully support ESM yet. There's some more details here: https://www.sitepen.com/blog/jest-esm-almost-there

**Comment by elf-pavlik** [comment]
Node 20 will be released in two weeks, I assume once the problems with native `fetch` implementations get resolved both 18 and 20 will be supported and included in the test matrix.
