### ISSUE TITLE
Session login TypeError: URL is not a constructor

### ISSUE THREAD

**Issue by Vidminas** [inrupt/solid-client-authn-js#2429]
### Search terms you've used

"URL not constructor". I also looked in the `openid-client` repo, but here seemed more relevant.

### Impacted package

Which packages do you think might be impacted by the bug ?

- [ ] solid-client-authn-browser
- [X] solid-client-authn-node
- [ ] solid-client-authn-core
- [ ] oidc-client-ext
- [ ] Other (please specify): ...

### Bug description

Session.login() throws an error when there shouldn't be one, and the error is also misleading.

### To Reproduce
I got a token id and secret from my Community Solid Server instance running at <https://solidpod.azurewebsites.net/>. Then I tried logging in with a new session using those:
```js
// id and secret definition omitted in example
const SOLID_IDENTITY_PROVIDER = "https://solidpod.azurewebsites.net";
const session = new Session();
session.login({
  clientId: id,
  clientSecret: secret,
  oidcIssuer: SOLID_IDENTITY_PROVIDER,
}
```
### Expected result

Successful login that gives me an authenticated fetch function.

### Actual result

`TypeError('only valid absolute URLs can be requested')` is thrown at line 69 of `node_modules/openid-client/lib/helpers/request.js`
Full stack trace:
```
Uncaught (in promise) TypeError: only valid absolute URLs can be requested
    at Issuer.request (request.js:69:11)
    at Issuer.discover (issuer.js:145:38)
    at IssuerConfigFetcher.fetchConfig (IssuerConfigFetcher.js:72:57)
    at OidcLoginHandler.handle (OidcLoginHandler.js:22:61)
    at ClientAuthentication.login (ClientAuthentication.js:13:57)
    at async Session.login (Session.js:16:31)
```

### Environment
Please run

  npx envinfo --system --npmPackages --binaries --npmGlobalPackages --browsers

in your project folder and paste the output here:

```
$ npx envinfo --system --npmPackages --binaries --npmGlobalPackages --browsers
 System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
    Memory: 7.84 GB / 15.89 GB
  Binaries:
    Node: 18.12.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (107.0.1418.35)
  npmPackages:
    @inrupt/solid-client: ^1.23.1 => 1.23.1
    @inrupt/solid-client-authn-browser: ^1.12.0 => 1.12.0
    @inrupt/solid-client-authn-node: ^1.12.2 => 1.12.2
    @inrupt/vocab-common-rdf: ^1.0.5 => 1.0.5
    assert: ^2.0.0 => 2.0.0
    buffer: ^6.0.3 => 6.0.3
    crypto-browserify: ^3.12.0 => 3.12.0
    css-loader: ^6.7.1 => 6.7.1
    expose-loader: ^4.0.0 => 4.0.0
    https-browserify: ^1.0.0 => 1.0.0
    image-picker: ^0.3.1 => 0.3.1
    jquery: ^3.6.1 => 3.6.1
    process: ^0.11.10 => 0.11.10
    smartwizard: ^6.0.6 => 6.0.6
    stream-browserify: ^3.0.0 => 3.0.0
    stream-http: ^3.2.0 => 3.2.0
    style-loader: ^3.3.1 => 3.3.1
    url: ^0.11.0 => 0.11.0
    util: ^0.12.5 => 0.12.5
    v8: ^0.1.0 => 0.1.0
    webpack: ^5.73.0 => 5.73.0
    webpack-cli: ^4.10.0 => 4.10.0
    webpack-dev-server: ^4.9.3 => 4.9.3
```

## Additional information

The relevant part inside `node_modules/openid-client/lib/helpers/request.js` is the following block:
```js
let url;
try {
  url = new URL(options.url);
  delete options.url;
  assert(/^(https?:)$/.test(url.protocol));
} catch (err) {
  throw new TypeError('only valid absolute URLs can be requested');
}
```
When I turned on the debugger and paused on exceptions, the first error it caught was: `err: TypeError: URL is not a constructor`, which was then discarded and the new TypeError was thrown. Debugger shows that `url` is set to `https://solidpod.azurewebsites.net/.well-known/openid-configuration`, and `url.protocol` is `https:` so the rethrown error is wrong.
At the same time, URL is `undefined` despite `const { URL } = __webpack_require__(/*! url */ "./node_modules/url/url.js");` at the top of the file and not being redefined anywhere in the file nor in my code.

This is a cut-down version of my webpack.config.js, if that's relevant:
```
const path = require("path");
const webpack = require("webpack");

module.exports = {
   mode: "development",
  // ...
  module: {
    rules: [
      {
        test: /\.css$/,
        use: [ { loader: "style-loader" }, { loader: "css-loader" } ],
      },
      {
        test: require.resolve("jquery"),
        loader: "expose-loader",
        options: {
          exposes: ["$", "jQuery"],
        },
      },
    ]
  },
  resolve: {
    fallback: {
      "assert": require.resolve("assert"),
      "crypto": require.resolve("crypto-browserify"),
      "http": require.resolve("stream-http"),
      "https": require.resolve("https-browserify"),
      "stream": require.resolve("stream-browserify"),
      "url": require.resolve("url"),
      "util": require.resolve("util"),
      "v8": require.resolve("v8")
    } 
  },
  plugins: [
    new webpack.ProvidePlugin({
        process: 'process/browser',
        Buffer: ['buffer', 'Buffer'],
    }),
  ],
// ...
};
```

Any ideas about what might be going wrong or how to debug further?

**Comment by jeswr** [comment]
> how to debug further?

Without digging into the logs above - have you tried following this page documenting the use of client-credentials with CSS https://communitysolidserver.github.io/CommunitySolidServer/5.x/usage/client-credentials/?

**Comment by Vidminas** [comment]
Hi Jesse! I did try, but hit a different snag with that approach: https://github.com/CommunitySolidServer/CommunitySolidServer/issues/1504

**Comment by jeswr** [comment]
Closing this since the linked issue to the CSS is resolved. Please re-open this if you have any outstanding questions.
