### ISSUE TITLE
crypto.getRandomValues() not supported.

### ISSUE THREAD

**Issue by ckemmler** [inrupt/solid-client-authn-js#2550]
### Search terms you've used

crypto.getRandomValues() solid inrupt

### Impacted package

- [ ] solid-client-authn-browser
- [x] solid-client-authn-node
- [ ] solid-client-authn-core
- [ ] oidc-client-ext
- [ ] Other (please specify): ...

### Bug description

Running a simple program built with rollup will crash with the following error 
```
/Users/xxx/work/sekund/solid-build-issues/main.js:5069
      throw new Error('crypto.getRandomValues() not supported. See https://github.com/uuidjs/uuid#getrandomvalues-not-supported');
            ^

Error: crypto.getRandomValues() not supported. See https://github.com/uuidjs/uuid#getrandomvalues-not-supported
```

### To Reproduce

1. Clone the repo at [https://github.com/ckemmler/solid-build-issues](https://github.com/ckemmler/solid-build-issues)
2. `npm install`
3. `npm run build`
4. `node main.js` <-- This is where the error occurs 

### Expected result

I would expect the program in the provided repo to successfully login using some credentials – those are left blank in the example but can easily be added. Note that the error is the same with and without valid credentials. Note also that valid credentials would be those resulting from following the "[register your application](https://login.inrupt.com/registration.html)" flow.

### Actual result

The following error is displayed in the console:

```
/Users/xxx/work/sekund/solid-build-issues/main.js:5069
      throw new Error('crypto.getRandomValues() not supported. See https://github.com/uuidjs/uuid#getrandomvalues-not-supported');
            ^

Error: crypto.getRandomValues() not supported. See https://github.com/uuidjs/uuid#getrandomvalues-not-supported
```

### Environment

```shell
$ npx envinfo --system --npmPackages --binaries --npmGlobalPackages --browsers

   System:
    OS: macOS 13.0
    CPU: (10) x64 Apple M1 Pro
    Memory: 127.67 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.16.0 - /usr/local/bin/node
    npm: 8.11.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 108.0.1
    Safari: 16.1
  npmPackages:
    @inrupt/solid-client-authn-node: ^1.12.3 => 1.12.3
    ldfetch: ^1.2.8 => 1.2.8
  npmGlobalPackages:
    n: 9.0.1
    npm: 8.11.0
    npx: 10.2.0
    webpack-bundle-analyzer: 4.5.0

```

## Additional information

The error given in the console points to [https://github.com/uuidjs/uuid#getrandomvalues-not-supported](https://github.com/uuidjs/uuid#getrandomvalues-not-supported)

...which essentially offers a mitigation strategy for libraries that use the `uuid` package. It looks like something that should be done upstream of my application, though.

**Comment by ThisIsMissEm** [comment]
It looks like your code is actually using `@inrupt/solid-client-authn-browser` from a node.js context. Currently authn doesn't work universally, so this would be the source of your problems:

https://github.com/ckemmler/solid-build-issues/blob/main/src/main.tsx#L1

if you intend to do authentication from within node.js, then you'll need to use `@inrupt/sllid-client-authn-node`. I do also note you have a react-native dependency in your package.json, and we don't currently officially support react-native

**Comment by ckemmler** [comment]
Good catch! Unfortunately switching to @inrupt/solid-client-authn-node doesn't solve the issue, as demonstrated by my last commit to my repro repo.

Essentially, it looks like the `crypto` function is simply not there. Could it be related to using commonjs?

**Comment by ThisIsMissEm** [comment]
Sorry, I can't assist you at the moment due to the holidays, there should be folks back in the next few days, or at the start of January. Try seeing if you can run your node.js program with out rollup.

I'll not be able to reply as I'm out sick with covid.

**Comment by ThisIsMissEm** [comment]
Your rollup config is also attempting to compile for browser. Try using just tsc instead of rollup

**Comment by ckemmler** [comment]
Sorry to hear you are sick with Covid and thank you for your support. I did successfully compile my program with tsc, so it looks like this issue is really more connected with my lack of understanding in things rollup.

I posted a question on StackOverflow (https://stackoverflow.com/questions/74921580/rollup-js-crypto-getrandomvalues-not-supported).

Take good care.
