### ISSUE TITLE
Memory leak when using onSessionRestore

### ISSUE THREAD

**Issue by mrkvon** [inrupt/solid-client-authn-js#2633]
I haven't found a way to unsubscribe from `onSessionRestore` (imported from `@inrupt/solid-client-authn-browser`).

So, when we use it in React as follows (based on [example from docs](https://docs.inrupt.com/developer-tools/javascript/client-libraries/tutorial/restore-session-browser-refresh/#use-session-restore-event-handler)):

```tsx

useEffect(() => {
  onSessionRestore(url => {
    // use react-router navigate = useNavigate()
    navigate(new URL(url).pathname)
  })
}, [navigate])
```

a new event listener gets created each time the `navigate` changes. But the old listener still exists, which leads to memory leak.

I'd expect API as follows:

```tsx
// create event listener
const subscription = onSessionRestore(handler)
// get rid of event listener
subscription.unsubscribe()
```

Then, we could use it in React as follows:

```tsx
useEffect(() => {
  const subscription = onSessionRestore(url => {
    // use react-router navigate = useNavigate()
    navigate(new URL(url).pathname)
  })

  // get rid of the old event listener when a new one is created
  // or when the contaning component gets unmounted
  return () => subscription.unsubscribe()
}, [navigate])
```

Or do i miss something?

**Comment by NSeydoux** [comment]
Hi @mrkvon, thanks for reaching out and sorry for the delayed response! What you describe sounds reasonable, we'll look at how best to address it. I'll keep this issue updated.

**Comment by jeswr** [comment]
Closing as resolved - @mrkvon feel free to re-open if you have any follow-ups.
