### ISSUE TITLE
Error `redirect` occurred during authentication for static server

### ISSUE THREAD

**Issue by qertis** [inrupt/solid-client-authn-js#2862]
### Impacted package

Which packages do you think might be impacted by the bug ?

- [x] solid-client-authn-browser

### Bug description

Hi there!

I'm using a PWA application and integrating your library. For the development environment, this is okay. But, when I build the production version of the PWA, I'm encountering a bug with authentication and seeing the error message: "redirect". 

### To Reproduce

1. To build a PWA with solid-client-authn-js

<details>

For example, use my [Pet project](https://github.com/gotois/archive)

```bash
git clone git@github.com:gotois/archive.git
npm i
npm run build
```

</details>

2. Run a local web server with CORS

<details>

For example, python simple server config:

```py
import os
from http.server import HTTPServer, SimpleHTTPRequestHandler

PORT = 22870

class CORSRequestHandler(SimpleHTTPRequestHandler):
    def end_headers(self):
        self.send_header('Access-Control-Allow-Origin', '*')
        self.send_header('Access-Control-Allow-Methods', 'GET')
        self.send_header('Cache-Control', 'no-store, no-cache, must-revalidate')
        return super(CORSRequestHandler, self).end_headers()

    def do_GET(self):
        if not os.path.exists(self.translate_path(self.path)):
            self.path = 'index.html'
        return SimpleHTTPRequestHandler.do_GET(self)

os.chdir('archive/dist/pwa')

httpd = HTTPServer(('localhost', PORT), CORSRequestHandler)

print("Serving at port", PORT)
httpd.serve_forever()
```

</details>

3. Attach error handlers

```js
import { EVENTS, events } from '@inrupt/solid-client-authn-browser'
events().on(EVENTS.ERROR, (error) => {
  console.log('Login error: ', error)
})
```

4. Run this code
 
```js
import {
  getDefaultSession,
  handleIncomingRedirect,
  login,
} from '@inrupt/solid-client-authn-browser'

/* ............................................. */

const defaultSession = getDefaultSession().info
console.log('defaultSession:', defaultSession)
const sessionInfo = await handleIncomingRedirect({
  restorePreviousSession: true,
})
console.log('oidcIssuer', oidcIssuer)
if (!sessionInfo) {
  console.log('try to login without sessionInfo')
  return login({
    oidcIssuer: 'https://login.inrupt.net',
    redirectUrl: 'http://localhost:22870/login',
    tokenType: 'DPoP',
    clientName: 'Contracts',
  })
}
```

### Expected result

I want to retrieve my WebId.

Login auth URL:
```
https://login.inrupt.com/authorization?client_id=c0541382-4bef-4c46-ade3-ec73ca7d0f91&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2F&response_type=code&scope=openid%20offline_access%20webid&state=536382cc486b4e1fabbc87bfd5f53d87&code_challenge=KZPkz_VZZNWrknQYAB_bKmOeQSnIf6GNbFWPIO4o3OQ&code_challenge_method=S256&prompt=consent&response_mode=query
```

### Actual result

I am not receiving my WebId. Instead, I am getting a "redirect" message. 

Login auth URL:
```
https://login.inrupt.com/authorization?client_id=30496907-716f-43f8-9264-4c5d11d460e9&redirect_uri=http://localhost:3000/?state=b959a53ea4414341b9d2883e70c215f2&response_type=code&scope=openid offline_access webid&state=08b05a64faa2464fa2a38f7f43313d23&code_challenge=cvHmXhXGKAiTGZ9wZFtPju_2ZwO6oubklH4uisuO_1M&code_challenge_method=S256&prompt=none&response_mode=query
```

Here's an example of the console call:
![image](https://user-images.githubusercontent.com/3893228/235490535-c22ac772-8bc0-4827-a96b-26783c35bbb8.png)

Browser requests:
![image](https://user-images.githubusercontent.com/3893228/235489662-2f4d49fe-1125-4233-941d-8c12fab6b24e.png)

**Comment by qertis** [comment]
More simplest example use Nuxt.

### Repo
https://github.com/qertis/bug

### Demo (Click button)
https://fastidious-torrone-33e006.netlify.app/

**Comment by qertis** [comment]
After trying to install your library from the source code, I stopped experiencing my issue. Based on my experience, it seems that your production build of the library, which uses Webpack, becomes incompatible with Vite.

It appears that anyone who wants to use your library with a Vite won't be able to use it. Please check building it with Vite.

**Comment by jeswr** [comment]
Hi @qertis - thanks for reporting!

Since the issue seems to be resolved for your case and hence not immediately blocking anything; we will look into this issue in the coming weeks :)
