### ISSUE TITLE
Resources return a 401 Unauthorized response

### ISSUE THREAD

**Issue by daytonn** [inrupt/solid-client-authn-js#290]
**Describe the bug**
Fetching any resource within my pod returns a `401 Unauthorized` response

**To Reproduce**
1. Within pod browser click on any resource to open the details panel
2. Notice that it cannot fetch the details and returns a 401

**Expected behavior**
When I attempt to fetch a resource within my pod, I receive the resource and 

**Screenshots**
![Peek 2020-09-02 17-55](https://user-images.githubusercontent.com/35955/92045204-9796f300-ed45-11ea-94b9-50dd7e8ea284.gif)

**Desktop (please complete the following information):**

- OS: PopOS 20.04 (Ubuntu 20.04)
- Firefox
- 80.0 (64-bit)

This seems to have something to do with the recent switch from `solid-auth-client`

**Comment by NSeydoux** [comment]
The issue was resolved offline. If I recall correctly, the session fetcher wasn't passed to one of the solid-client functions. Anyways, this can't be reproduced with the latest version.
