### ISSUE TITLE
ESM distro for @inrupt/solid-client-authn-browser

### ISSUE THREAD

**Issue by riovir** [inrupt/solid-client-authn-js#3001]
**UPDATE 2**: Here's a small [reproduction on Codesandbox](https://codesandbox.io/p/sandbox/vite-forked-vs5l4c) make sure to interact with the preview on a separate browser tab to avoid a login-loop.
**UPDATE**: Changed workaround to use a more idiomatic way to force ESM transitive dependencies for Rollup / Vite.

### Search terms you've used

- esm
- rollup
- vite

### Impacted environment

In which environment would the proposed feature apply?

- [x] The browser (with a bundler)
- [ ] Node.js
- [ ] Other (please specify): ...
- [ ] I'm not sure.

### Feature suggestion

The @inrupt/solid-client-authn-browser/package.json declares a valid ESM export. (With either an mjs extension or also the "type": "module" set).

### Expected functionality/enhancement

It would be possible to use the package with modern bundlers, such as Vite.

### Actual functionality/enhancement

When Vite does a production build the app seemingly works, but fails at runtime. The rabbit hole looks like this:
- Vite uses Rollup for production builds (instead of ESBuild used during development)
- Rollup concludes that @inrupt/solid-client-authn-browser is in CommonJS
- Then, when processing the transitive dependencies, eventually imports the `@inrupt/solid-client-authn-core` however, picks the CommonJS edition. This edition, has been written with Node.js in mind, trying to use the `node-fetch` instead of the readily available `fetch` in the browser.

The ideal way to break that chain is to offer an ESM edition of the `@inrupt/solid-client-authn-browser` so that bundlers won't try to pick the CJS / Node version of transitives.

### Use Cases

Trying to build a basic Vue.js app with Vite instead of Webpack. The Vue community has been slowly backing away from Webpack, instead putting their effort into Vite (ESBuild for dev, Rollup for prod builds). Unfortunately, without hacking into node_modules with `patch-package` I was unable to create a working production build.

### Additional information

As a workaround I explicitly list most of the transitive dependencies of `@inrupt/solid-client-authn-browser` and use a `customResolver` that's [forced to pick ESM versions](https://gitlab.com/riovir/babalog/-/blob/27d0f8e35c3c9e0d28af04f342416dae398f9f47/vite.config.ts#L23-26)

~~As a workaround / [hack I patched up the @inrupt/solid-client-authn-core](https://gitlab.com/riovir/babalog/-/blob/d08d9e88dd56b03acb69a60fe549980fb5827d7b/patches/%40inrupt%2Bsolid-client-authn-core%2B1.16.0.patch) package locally, to expose its ESM build even when require is in use. Mostly to avoid using the node-fetch that fails in the browser. However ideally, I hoped that the bundler can pick a browser / ESM targeted format of the packages.~~

Note that a fix for this would likely close #1815 as well. Also note that 2 more adjustments seemed to be necessary so that the project builds: https://gitlab.com/riovir/babalog/-/blob/main/vite.config.ts#L20-21

**Comment by jeswr** [comment]
Thanks for reporting - we will look into this.

> Then, when processing the transitive dependencies, eventually imports the @inrupt/solid-client-authn-core however, picks the CommonJS edition. This edition, has been written with Node.js in mind, trying to use the node-fetch instead of the readily available fetch in the browser.

I'm surprised this is happening; note that @inrupt/solid-client-authn-core and @inrupt/solid-client-authn-browser both use @inrupt/universal-fetch under the hood which should only resolve to node-fetch when targeting node environments (with versions of node lower than 16.8 - see https://github.com/inrupt/universal-fetch/blob/main/src/index.ts).

What error were you getting that indicated this was happening and/or do you have a minimal repro?

> Also note that 2 more adjustments seemed to be necessary so that the project builds

The `stream` patch is due to this upstream issue https://github.com/nodejs/readable-stream/issues/516 (which we have proposed a patch for in https://github.com/nodejs/readable-stream/pull/520).

What error were you getting that required the `'util': 'util/',` entry?

**Comment by riovir** [comment]
> What error were you getting that indicated this was happening and/or do you have a minimal repro?
Without the patch hack, ESBuild (development mode of Vite) works correctly. (Cool, let's deploy!) Then to my surprise, the prod build was unable to log me into my pod provider. Instead, the page just seemingly reloaded and nothing happened. To I grabbed a console.log and dove head first into node_modules. Turned out that the CJS edition of the transitive dependencies was bundled in, and the universal-fetch trying to use node-fetch silently failed (a catch block swallowed the error). Therefore I was never able to reconstruct the Session. That prompted me to find a way to force ESM editions to the transitive packages required by `@inrupt/solid-client-authn-browser`. The reason this is not an issue with Webpack is that it was designed to consume CJS packages for the web.

> both use @inrupt/universal-fetch under the hood which should only resolve to node-fetch when targeting node environments

The `@inrupt/solid-client-authn-core` is in fact correct. My hack messes with it as an innocent bystander. What really happens is as I understand it that `@inrupt/solid-client-authn-browser` lacking a `"type": "module"` (and a `.mjs` extension) in its package json, signals to Vite (Rollup in fact, as it happens during the prod build) that it `.js` extensions mean that they are in CommonJS. Then Vite/Rollup will pick the CJS editions of transitive dependencies even though it'd prefer ESM. The assumption of `@inrupt/solid-client-authn-core` is that when its CJS edition is loaded it's done for the server. However, `@inrupt/solid-client-authn-browser`'s config causes the bundler to resolve CJS for the code intended for the browser.

> What error were you getting that required the 'util': 'util/', entry?

Unless I have it there I get:
```
chunk-AC2VUBZ6.js?v=59b0ec33:11 Module "util" has been externalized for browser compatibility. Cannot access "util.inspect" in client code. See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
```

That said, the code doesn't seem to need it at runtime. I suspect that the code is only needed when the packages are used on Node.js. The CJS format of `@inrupt/solid-client-authn-browser` seems to be the one causing the pull-in code intended for the server into the browser context.

**Comment by riovir** [comment]
**Update:** by explicitly listing the dependencies of `@inrupt/solid-client-authn-browser` and [forcing the bundler to pick the ESM versions of them](https://gitlab.com/riovir/babalog/-/blob/27d0f8e35c3c9e0d28af04f342416dae398f9f47/vite.config.ts#L23-26) the build also works, and the `'util': 'util/'` entry is indeed unnecessary.

That said, this needs quite some dive into the Vite / Rollup config, plus an understanding of why the bundler gets confused by the CJS format of the browser library. An ESM build would be a big step toward a happy out-of-the-box experience.

**Comment by riovir** [comment]
I've created a small reproduction on Codesandbox: https://codesandbox.io/p/sandbox/vite-forked-vs5l4c

**Comment by riovir** [comment]
I also noticed that it's not CJS per se that causes the issue in the `@inrupt/solid-client-authn-core` but the use of fetch via a Node polyfill. However, to my knowledge, the fetch() has been stable since Node 18, so it may be worthwhile to consider dropping the universal-fetch / node-fetch transitive and favoring the built-in fetch() or the current platform. (Depending on how far back Inrupt supports Node)

**Comment by elf-pavlik** [comment]
We encountered a problem using `@inrupt/solid-client-authn-browser` with node 16, pinning node to 18 solved the problem for us so we didn't investigate further. I recall an error being thrown somewhere inside of ` @inrupt/solid-client-authn-core` so it could be related. I could try to reproduce it and report it properly.

**Comment by jeswr** [comment]
SWhat universal fetch does is:
 - On Node 18 and above the global fetch is used
 - On Node ^16.8 and Node 17; the `undici` package is imported and used
 - On other versions of Node `node-fetch` is used

An error report would be useful @elf-pavlik as I am not expecting such a change in behavior between Node 16 and Node 18.

**Comment by elf-pavlik** [comment]
reported in https://github.com/inrupt/solid-client-authn-js/issues/3004 and fails in the `undici` package you mentioned above

**Comment by riovir** [comment]
Appreciate the update! I could remove a big chunk of Vitest code to make sure the `@inrupt/solid-client-authn-browser` works.
In fact, I have zero lines in my `vitest.config.ts` related to SOLID. I'm a happy developer.
