### ISSUE TITLE
Problem with InMemoryStorage re-exported in solid-client-authn-node

### ISSUE THREAD

**Issue by elf-pavlik** [inrupt/solid-client-authn-js#3068]
### Search terms you've used

InMemoryStorage

### Impacted package

Which packages do you think might be impacted by the bug ?

- [ ] solid-client-authn-browser
- [x] solid-client-authn-node
- [ ] solid-client-authn-core
- [ ] oidc-client-ext
- [ ] Other (please specify): ...

### Bug description

The problem appeared after a recent change to ESM modules. We were importing `InMemoryStorage` in our tests from `solid-client-authn-node` and before it worked just fine.
Our CI doesn't use a lock file and during recent commit ts-jest failed with

```
TypeError: solid_client_authn_node_1.InMemoryStorage is not a constructor
```

As a quick fix, I changed to importing `InMemoryStorage` directly from `solid-client-authn-core` and now it works just fine

https://github.com/janeirodigital/sai-js/commit/10b0202a667742cac4423d410c054884ebfc5234

### To Reproduce

See failing CI job: https://github.com/janeirodigital/sai-js/actions/runs/5623982917/job/15244390686#step:7:294

**Comment by jeswr** [comment]
Thanks for reporting - we will look into this.

**Comment by jeswr** [comment]
The problem appears to be the way you're mocking the module. In particular replacing 

```ts
jest.mock('@inrupt/solid-client-authn-node');
```

with

```ts
jest.mock('@inrupt/solid-client-authn-node', () => ({
  InMemoryStorage: jest.requireActual<{ InMemoryStorage: InMemoryStorage }>('@inrupt/solid-client-authn-node').InMemoryStorage,
}));
```
fixes the issue in my minimal repro and so should also fix the problem in packages/service/test/unit/handlers/authorization-agent-context-handler-test.ts

---

The following is a detail of tests I have done to make sure `InMemoryStorage` can be accessed as expected in mjs and cjs land.

----

I've tested the following cjs and mjs scripts. Both work on 1.17.1 of authn-node

test.js
```js
const { InMemoryStorage } = require('@inrupt/solid-client-authn-node');

const storage = new InMemoryStorage()
storage.set('https://example.com', 'my-token')
console.log(storage.get('https://example.com'))
```

test.mjs
```js
import { InMemoryStorage } from '@inrupt/solid-client-authn-node';

const storage = new InMemoryStorage()
storage.set('https://example.com', 'my-token')

console.log(storage.get('https://example.com'))
```
---
With `ts-jest` I've tried the following test.ts

```test.ts
import { describe, it, expect } from "@jest/globals";
import { InMemoryStorage } from '@inrupt/solid-client-authn-node';

describe("InMemoryStorage", () => {
  it("Should work", () => {

    const storage = new InMemoryStorage()
    storage.set('https://example.com', 'my-token')

    return expect(storage.get('https://example.com')).resolves.toBe('my-token')
  })
});
```
and jest.config.js
```ts
/** @type {import('ts-jest').JestConfigWithTsJest} */
module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
};
```
and tests pass

---

For reference all of the above has been done with the following package.json
```json
{
  "name": "authn-version-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "jest test.ts"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@inrupt/solid-client-authn-node": "^1.17.1"
  },
  "devDependencies": {
    "ts-jest": "^29.1.1"
  }
}
```

**Comment by elf-pavlik** [comment]
Of course! Since changing my import from `-node` to `-core` package solved it I assumed that there was some issue with re-exporting. But you are absolutely right that it worked because `-core` is not mocked with jest.

I also got a bit misled by the test starting to fail with the latest version of `-node`, while it was passing before.

My apologies for not investigating deeper before reporting!
