### ISSUE TITLE
Error when following readme instructions

### ISSUE THREAD

**Issue by skandarchahbouni** [inrupt/solid-client-authn-js#3116]
![image](https://github.com/inrupt/solid-client-authn-js/assets/90493112/bdf2bdf6-a1ab-4a10-a5ab-fdcac85a2958)
I am getting this error when I ran this commands which i found in the readme file :

git clone https://github.com/inrupt/solid-client-authn-js
cd solid-client-authn-js
npm ci
cd packages/node/example/demoClientApp/
npm ci
npm run start

please I will appreciate any help you can provide to solve this issue

**Comment by jeswr** [comment]
This issue is also discussed in https://forum.solidproject.org/t/error-when-following-the-tutorial-authentication-client-section/6865. The current suggestion is for windows users to try the fix discussed [here](https://github.com/lerna/lerna/issues/3612) in the lerna repo.

**Comment by NSeydoux** [comment]
https://github.com/inrupt/solid-client-authn-js/pull/3115 should fix this. Let me know if the problem persists.
