### ISSUE TITLE
Installation issues on Windows

### ISSUE THREAD

**Issue by joachimvh** [inrupt/solid-client-authn-js#3117]
### Search terms you've used

Windows

### Impacted package

Which packages do you think might be impacted by the bug ?

- [x] solid-client-authn-browser
- [x] solid-client-authn-node
- [x] solid-client-authn-core
- [x] oidc-client-ext
- [x] Other (please specify): I assume this is a core issue with the entire repository

### Bug description

There seem to be several issues related to installing the package on Windows from the source. Last time I cloned and installed from the repo was version 1.16.0 at which point I had no issues. So the problem must have been introduced somewhere between then and 1.17.1.

When running `npm ci` in the root of the project on Windows, the error `Error: Cannot find module '@nx/nx-win32-x64-msvc'` is thrown and the build is cancelled. Looking around this seems to be a consequence of not having a specific Windows redistributable installed, but after making sure it was installed I still have the same issue. I discovered that removing the `package-lock.json` and running `npm i` to generate a new one did solve the problem mostly, so it might be an issue with an outdated dependency somewhere.

I say mostly, because after that one of the build steps still fails with the following error:
```
    ×  @inrupt/demo-app-authn-browser:build
       > @inrupt/demo-app-authn-browser@1.17.1 build
> ASSET_PATH="/demo/" webpack --mode productiond for 10 projects

'ASSET_PATH' is not recognized as an internal or external command,
       operable program or batch file.
```
which has to do with the different way Windows sets environment variables. If necessary, something like `cross-env` can probably be used to fix this. This is the same issue as described in https://github.com/inrupt/solid-client-authn-js/issues/3116.

See also https://github.com/CommunitySolidServer/tutorials/issues/5 for additional comments which is how I found this.

### To Reproduce

1. `git clone https://github.com/inrupt/solid-client-authn-js.git`
2. `cd solid-client-authn-js`
3. `npm ci`

### Environment

Please run

npx envinfo --system --npmPackages --binaries --npmGlobalPackages --browsers

in your project folder and paste the output here:

```
$ npx envinfo --system --npmPackages --binaries --npmGlobalPackages --browsers
  System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 4.65 GB / 15.73 GB
  Binaries:
    Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.15 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (116.0.1938.62)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @inrupt/base-rollup-config: ^2.1.2 => 2.1.3
    @inrupt/eslint-config-lib: ^2.1.3 => 2.1.3
    @inrupt/internal-playwright-helpers: ^2.1.3 => 2.1.3
    @inrupt/internal-test-env: ^2.1.0 => 2.1.3
    @inrupt/jest-jsdom-polyfills: ^2.1.2 => 2.1.3
    @playwright/test: ^1.36.2 => 1.37.1
    @rollup/plugin-commonjs: ^25.0.4 => 25.0.4
    @rollup/plugin-node-resolve: ^15.1.0 => 15.2.1
    @rollup/plugin-terser: ^0.4.3 => 0.4.3
    @types/dotenv-flow: ^3.3.0 => 3.3.0
    @types/http-link-header: ^1.0.3 => 1.0.3
    @types/jest: ^29.5.3 => 29.5.4
    @typescript-eslint/eslint-plugin: ^5.6.0 => 5.62.0
    @typescript-eslint/parser: ^5.62.0 => 5.62.0
    dotenv-flow: ^3.3.0 => 3.3.0
    eslint: ^8.25.0 => 8.48.0
    eslint-config-next: ^13.4.13 => 13.4.19
    express: ^4.18.2 => 4.18.2
    http-link-header: ^1.1.0 => 1.1.1
    jest: ^29.6.1 => 29.6.4
    jest-environment-jsdom: ^29.6.1 => 29.6.4
    jest-mock-console: ^1.2.3 => 1.3.0
    lerna: ^7.1.0 => 7.2.0
    lerna-audit: ^1.3.3 => 1.3.3
    license-checker: ^25.0.1 => 25.0.1
    prettier: ^3.0.2 => 3.0.3
    rimraf: ^5.0.0 => 5.0.1
    rollup: ^3.26.3 => 3.28.1
    rollup-plugin-typescript2: ^0.35.0 => 0.35.0
    ts-jest: ^29.1.1 => 29.1.1
    ts-loader: ^9.1.1 => 9.4.4
    ts-node: ^10.9.1 => 10.9.1
    tsc-watch: ^5.0.2 => 5.0.3
    typedoc: ^0.25.0 => 0.25.0
    typedoc-plugin-markdown: ^3.15.4 => 3.16.0
    typescript: ^5.1.3 => 5.2.2
  npmGlobalPackages:
    corepack: 0.10.0
    npm: 8.1.2
    serve: 14.2.0
```
Note that this is the output after successfully installing by removing the `package-lock.json`.

**Comment by NSeydoux** [comment]
Hi @joachimvh , thanks for reaching out. I also reproduced the issue in CI after it had been reported on https://forum.solidproject.org/t/error-when-following-the-tutorial-authentication-client-section/6865. We'll see what can be done about this, it looks like it is related to some issue with Lerna/Nx.

**Comment by NSeydoux** [comment]
https://github.com/inrupt/solid-client-authn-js/pull/3115 should resolve this issue. The CI now passes on windows.
