### ISSUE TITLE
This module is declared with 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.

### ISSUE THREAD

**Issue by bourgeoa** [inrupt/solid-client-authn-js#3219]
### Impacted package

Which packages do you think might be impacted by the bug ?

- [ x] solid-client-authn-browser
- [ ] solid-client-authn-node
- [ ] solid-client-authn-core
- [ ] oidc-client-ext
- [ ] Other (please specify): ...

### Bug description

node_modules/@inrupt/solid-client-authn-browser/dist/Session.d.ts:7:8 - error TS1259: Module '"events"' can only be default-imported using the 'allowSyntheticDefaultImports' flag

7 import EventEmitter from "events";
         ~~~~~~~~~~~~

  node_modules/@types/node/events.d.ts:673:5
    673     export = EventEmitter;
            ~~~~~~~~~~~~~~~~~~~~~~
    This module is declared with 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.

Found 1 error in node_modules/@inrupt/solid-client-authn-browser/dist/Session.d.ts:7

### To Reproduce

1.
2.
3.
4.

### Actual result

unable to build contacts-pane in SolidOS stack

### Environment

node 16 and 18

**Comment by NSeydoux** [comment]
Thanks for reporting this @bourgeoa , we'll look into this soon. Can you specify which toolchain was being used to do the build? 

Just as a follow-up comment, we will soon remove support for Node 16, as Node 16 has been end-of-lifed.

**Comment by bourgeoa** [comment]
The SolidOS build is a bit complex.

https://github.com/SolidOS/contacts-pane

May be this can help. it is the local build that failed

contacts-pane# npm ls @inrupt/solid-client-authn-browser@1.17.3
contacts-pane@2.6.10 /mnt/d/github/source/workspaces/contacts-pane
└─┬ solid-ui@2.4.29
  └─┬ solid-logic@3.0.4
    └── @inrupt/solid-client-authn-browser@1.17.3

**Comment by NSeydoux** [comment]
Hi @bourgeoa, I haven't had time to look into this deeply yet, I don't anticipate that will be the case before the new year. At what stage of the build is the issue happening? My current hypothesis is that the issue comes from the interaction with `tsc-transpile-only`, because I don't see this issue in other projects importing this library using the regular `tsc`. Have you tried adding the mentioned `allowSyntheticDefaultImports` flag to your `tsonfig.json`?

**Comment by bourgeoa** [comment]
@NSeydoux , thanks this is working.
I did not understand I had to solve it on my side.

@timbl issue resolved,
