### ISSUE TITLE
Support for solid-auth-client's ".on" function

### ISSUE THREAD

**Issue by james-martin-jd** [inrupt/solid-client-authn-js#35]
When trying to upgrade an existing library, I ran into a blocker. The solid/react-components library (and by extension, the React SDK) uses LiveUpdates and websockets, which under the hood uses a `.on` call. It seems the current fetcher does not support .on yet.

**Comment by nicolasmondada** [comment]
This is available under the Session object, for example: [onLogin](https://docs.inrupt.com/developer-tools/api/javascript/solid-client-authn-browser/classes/Session.html#onlogin)
