### ISSUE TITLE
Points from documentation code review

### ISSUE THREAD

**Issue by jaxoncreed** [inrupt/solid-client-authn-js#38]
- At the beginning explain that in this case the server is a client
- Write a tutorial
- Eliminate the word “client” from the first sentence
- Move server example to 3rd example
- Add more prose about needed action
    - Login and session say that a session isn’t always logged in. Sometimes it has a needed action
- Have an option for unique login

**Comment by nicolasmondada** [comment]
All these comments have long been addressed in the readme and [docs.](https://docs.inrupt.com/developer-tools/javascript/client-libraries/tutorial/authenticate/)
