### ISSUE TITLE
Allow strings to be passed into the Login input

### ISSUE THREAD

**Issue by jaxoncreed** [inrupt/solid-client-authn-js#420]
Currently, only URLs are allowed to be passed for a redirect URL and an OIDC issuer (https://github.com/inrupt/solid-client-authn-js/blob/master/packages/core/src/ILoginInputOptions.ts#L28-L32).

While I agree that internally it makes sense to pass around URLs, an external interface should allow strings then error if they are not valid URLs. Additionally, this requires a "url-parse" URL, not the kind you get by default in the web browser.

**Comment by pmcb55** [comment]
Good point! I've added a ticket to track this - could be important when we add the extra environment support (e.g. NodeJS, native, etc.)

**Comment by pmcb55** [comment]
Hi Jackson - we cut release 0.3.0 on Friday which includes this change. Thanks again.
