### ISSUE TITLE
Unable to fetch when not logged in

### ISSUE THREAD

**Issue by jaxoncreed** [inrupt/solid-client-authn-js#441]
Hey everyone, sorry for more github issues. I know you're all busy.

**Describe the bug**
If you try to make a fetch using the auth session, it will cause an error: `Error: Could not obtain the key to sign the token with.`

**To Reproduce**

1. Set up the single/bundle example (https://github.com/inrupt/solid-client-authn-js/tree/master/packages/browser/examples/single/bundle)
2. Replace `App.js` with the code here: https://gist.github.com/jaxoncreed/76c7c63a497c191fd6cb357d2f204d86
3. Run the example
4. Before logging in, press the "Unauthenticated Fetch" button which should send a fetch request to a public profile.
5. The app will hang on the "loading" screen. If you open the debug console, you'll see the error logged. 

**Expected behavior**
The fetcher should attempt to make an unauthenticated fetch and only fail if that resource is not public.

**Environment**

```
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 576.42 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.4.0 - /usr/local/bin/node
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 86.0.4240.80
    Firefox: 81.0.1
    Safari: 14.0
  npmPackages:
    @babel/core: ^7.8.6 => 7.10.5 
    @babel/preset-env: ^7.8.6 => 7.10.4 
    @babel/preset-react: ^7.8.3 => 7.10.4 
    @inrupt/solid-client-authn-browser: file://../../../ => 0.2.1 
    babel-loader: ^8.0.6 => 8.1.0 
    html-loader: ^0.5.5 => 0.5.5 
    html-webpack-plugin: ^3.2.0 => 3.2.0 
    react: ^16.13.0 => 16.13.1 
    react-dom: ^16.13.0 => 16.13.1 
    regenerator-runtime: ^0.13.3 => 0.13.7 
    webpack: ^4.41.6 => 4.44.0 
    webpack-cli: ^3.3.11 => 3.3.12 
    webpack-dev-server: ^3.10.3 => 3.11.0 
  npmGlobalPackages:
    @inrupt/generator-solid-react: 0.7.2
    @inrupt/solid-auth-fetcher: 0.0.6
    expo-cli: 3.27.4
    lerna: 3.22.1
    npm: 6.14.4
    ochat-api: 1.0.0
    redis-commander: 0.7.0
    static-server: 2.2.1
    typescript: 3.9.5
    yo: 3.1.1
```

**Additional context**
@NSeydoux previously implemented this, but it looks like it was removed.

The error is triggered here: https://github.com/inrupt/solid-client-authn-js/blob/b9fd0de31b3a85e848a056224acf63faf45a2346/packages/browser/src/dpop/DpopHeaderCreator.ts#L65. It happens after a dpop key cannot be fetched from storage. It looks like this still uses the old storage system, so this is probably happening because of the change in storage systems.

**Comment by pmcb55** [comment]
Hi Jackson - so I just tried to reproduce this, but it worked fine for me.
![Issue-441 2020-10-20 18-04](https://user-images.githubusercontent.com/961445/96620053-d3d6e080-12fe-11eb-855d-6d53e6e3932b.gif).
Is this still happening for you...?

**Comment by pmcb55** [comment]
Actually Jackson - I notice in your environment report, the dependency on ` @inrupt/solid-auth-fetcher: 0.0.6`.

My codebase has `@inrupt/solid-auth-fetcher: 0.0.6` - in file `packages/browser/examples/single/bundle/package.json`, and in fact we're working with the `1.x` branch as our main branch at the moment (we'll be re-aligning back to `master` very soon, just temporary internal jiggery-hokery at the moment!). Can you try that branch (https://github.com/inrupt/solid-client-authn-js/tree/1.x)...?

**Comment by pmcb55** [comment]
Sorry - typo in my comment above - my codebase has ` "@inrupt/solid-client-authn-browser": "file://../../../"` (and **_not_** `@inrupt/solid-auth-fetcher: 0.0.6` - sorry!) (and thanks to @Vinnl for pointing that out to me :) !)

**Comment by Vinnl** [comment]
Heads-up: branches are deployed to npm, and the branch Pat was referring to is now merged to `master`. So you should be able to try it out by running `npm install @inrupt/solid-client-authn-browser@master`.

**Comment by jaxoncreed** [comment]
Got it. The branch was outdated. Thanks!
