### ISSUE TITLE
Move away from hybrid flow

### ISSUE THREAD

**Issue by jaxoncreed** [inrupt/solid-client-authn-js#472]
Currently solid-client-authn-js triggers a hybrid login flow by setting `response_type=code%20id_token`. Per @acoburn 's suggestion, hybrid flow should not be used.

**Comment by NSeydoux** [comment]
Which version are we talking about ? In the latest codebase, only the auth code flow with PKCE token and implicit flows are supported (resp https://github.com/inrupt/solid-client-authn-js/blob/55b68fd0b9b71f365875398b29f85e66332dea1e/packages/browser/src/login/oidc/oidcHandlers/AuthorizationCodeWithPkceOidcHandler.ts#L67, https://github.com/inrupt/solid-client-authn-js/blob/55b68fd0b9b71f365875398b29f85e66332dea1e/packages/browser/src/login/oidc/oidcHandlers/LegacyImplicitFlowOidcHandler.ts#L76). In which context do you get a hybrid flow triggered ?

**Comment by jaxoncreed** [comment]
Ah perfect. I might have been looking at an older version.
