### ISSUE TITLE
Regex for `sub` claim doesn't allow localhost

### ISSUE THREAD

**Issue by jaxoncreed** [inrupt/solid-client-authn-js#551]
The regex here (https://github.com/inrupt/solid-client-authn-js/blob/49cf2fa71af372f7b156ccd1ca4006a995c74ba6/packages/oidc/src/dpop/tokenExchange.ts#L111) doesn't allow for a domain like `https://localhost:8443/profile/card#me`. Because NSS does not issue a `webid` claim, a user running NSS on single-user mode locally is not able to log in.

**Comment by nicolasmondada** [comment]
Good catch! Thanks for reporting this @jaxoncreed.
