### ISSUE TITLE
Discuss/clarify why there needs to be an ID for a session

### ISSUE THREAD

**Issue by RubenVerborgh** [inrupt/solid-client-authn-js#58]
From #28:

> > localUserId is weird; not sure it belongs here. What problem are we solving?

> There must be some kind of ID to identify the session. Because not all sessions are logged in, the webId cannot be used.

I'd like to take 2–3 steps back here to identify the high-level problem. (ID already being a possible solution.)

What exactly is the problem we are solving? Distinguishing multiple simultaneous sessions? What does it mean to have a session that is not logged in? Etc.

**Comment by jaxoncreed** [comment]
Hopefully the new documentation makes this clearer.

**Comment by nicolasmondada** [comment]
Using sessionIds is documented [here](https://docs.inrupt.com/developer-tools/javascript/client-libraries/tutorial/authenticate-nodejs/#node-js-web-server-multi-session-management). This issue is closed.
