### ISSUE TITLE
Enabling components to listen to any server-side change

### ISSUE THREAD

**Issue by RubenVerborgh** [inrupt/solid-client-authn-js#64]
## Need
- The Solid React components currently offer a way to listen to _any_ changes (in addition to specific changes).
- Currently, this _any_ is determined by subscribing to updates for every target URL of an outgoing HTTP request.
  - For example, if requests are made to `http://a.com/12`, `http://b.com/45`, then the React components will subscribe to the WebSockets running on both hosts, and trigger a refresh on _any_ pub event.

## Solution in solid-auth-client
- A `request` event is exposed, such that the React components see _every_ request that is made with the fetcher.
  - Based on these URLs, a WebSocket is set up to every unique host.

## Concerns with the existing solution
- solid-auth-client leaks all requests that _any_ client-side library makes to _all_ client-side librariess, which is a potential security issue.

## Solution paths
- only expose hosts or WebSocket URLs (which are roughly equivalent; one comes from the other)
  - very solution-specific though
  - perhaps also a security problem
- remove the listen _all_ functionality from the React components
  - then only listening to _specific_ resources will be supported

**Comment by michielbdejong** [comment]
@NSeydoux Are you working on this? We need Websockets support for https://github.com/solid/node-solid-ws/issues/1#issuecomment-708371829.

Would you accept a pull request?

**Comment by nicolasmondada** [comment]
This should be discussed in https://github.com/inrupt/solid-client-notifications-js.
