### ISSUE TITLE
Unauthenticated fetch causes TypeError: 'fetch' called on an object that does not implement interface Window

### ISSUE THREAD

**Issue by RubenVerborgh** [inrupt/solid-client-authn-js#944]
### Impacted package

Which packages do you think might be impacted by the bug ?

- [x] solid-client-authn-browser
- [ ] solid-client-authn-node
- [ ] solid-client-authn-core
- [ ] oidc-client-ext
- [ ] Other (please specify): ...

### Bug description
When upgrading https://github.com/RubenVerborgh/solid-patch-tool from v1.1.1 to 1.4.0, the same code now crashes with
> TypeError: 'fetch' called on an object that does not implement interface Window

### To Reproduce
1. Go to https://rubenverborgh.github.io/solid-patch-tool/
2. Click "Apply patch" (without first logging in)
3. 
4. 

### Expected result
It does a normal fetch

### Actual result
It crashes

### Environment
Please run

  npx envinfo --system --npmPackages --binaries --npmGlobalPackages --browsers

in your project folder and paste the output here:

```
  System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 363.47 MB / 16.00 GB
    Shell: 5.0.18 - /usr/local/bin/bash
  Binaries:
    Node: 14.4.0 - ~/.nvm/versions/node/v14.4.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.9 - ~/.nvm/versions/node/v14.4.0/bin/npm
  Browsers:
    Chrome: 87.0.4280.141
    Firefox: 84.0.2
    Safari: 14.0.2
  npmPackages:
    @inrupt/solid-client-authn-browser: ^1.4.0 => 1.4.0
    webpack: ^4.44.2 => 4.44.2
    webpack-cli: ^4.2.0 => 4.2.0
```

**Comment by NSeydoux** [comment]
Thanks for reporting this ! I'll investigate first thing tomorrow morning.

**Comment by NSeydoux** [comment]
Release 1.4.1 should include the fix for this issue.

**Comment by matthieu-fesselier** [comment]
I currently face exactly the same issue:
```
  System:
    OS: macOS 11.3
    CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
    Memory: 2.05 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.9.0 - /usr/local/bin/node
    npm: 7.5.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 90.0.4430.212
    Firefox: 88.0.1
    Safari: 14.1
  npmPackages:
    @inrupt/solid-client-authn-browser: 1.8 => 1.8.1
    @startinblox/core: ^0.15.6 => 0.15.6
    babel-eslint: ^10.1.0 => 10.1.0
    buffer: ^6.0.3 => 6.0.3
    crypto-browserify: ^3.12.0 => 3.12.0
    eslint: ^7.0.0 => 7.19.0
    eslint-config-airbnb-base: ^14.1.0 => 14.2.1
    eslint-plugin-import: ^2.20.2 => 2.22.1
    express: ^4.17.1 => 4.17.1
    find-free-port: ^2.0.0 => 2.0.0
    reflect-metadata: ^0.1.13 => 0.1.13
    stream-browserify: ^3.0.0 => 3.0.0
    util: ^0.12.3 => 0.12.3
    webpack: ^5.21.2 => 5.21.2
    webpack-cli: ^4.5.0 => 4.5.0
  npmGlobalPackages:
    cypress: 6.3.0
    gatsby-cli: 3.3.0
    mrm: 2.6.2
    npm: 7.5.3
    react-devtools: 4.11.0
```

**Comment by Vinnl** [comment]
@matthieu-fesselier Would it be possible for you to provide a minimal reproduction of the issue? I can't seem to reproduce it here: https://codesandbox.io/embed/clever-lewin-bhgny

And/or possibly share the output of `npm ls @inrupt/solid-client-authn-browser`?

**Comment by matthieu-fesselier** [comment]
Sure, I'm basically doing something like this: https://codesandbox.io/s/epic-tree-333vr?file=/src/index.js 
```
▶ npm ls @inrupt/solid-client-authn-browser
@startinblox/oidc@0.0.0 /Users/matthieu/sites/sib/components/sib-auth
└── @inrupt/solid-client-authn-browser@1.8.1
```

**Comment by Vinnl** [comment]
Gotcha, thanks for the prompt response! I'll investigate.

**Comment by Vinnl** [comment]
Hi @matthieu-fesselier, this should be fixed in release 1.9.1, which should be published when [this CI job](https://github.com/inrupt/solid-client-authn-js/actions/runs/968109955) finishes. Feel free to open a new issue if you experience further problems. Cheers!

**Comment by matthieu-fesselier** [comment]
Sorry for the delay, I was off for a few days. I tested it and it seems to work fine on our side, thanks a lot!

**Comment by Vinnl** [comment]
Perfect, thanks for reporting back!
